<script setup lang="ts">
import {computed,ref,watch,onUnmounted,nextTick} from 'vue';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import type {ProjectDraft} from '../../shared/project-draft';
import type {ProjectDagCreationPreparation,ProjectDagCreationResult} from '../../shared/project-dag';
const props=defineProps<{draft:ProjectDraft|null}>();const emit=defineEmits<{close:[]}>();
const projectPath=ref(''),baseBranch=ref(''),verification=ref(''),busy=ref(false),reviewed=ref(false),error=ref('');
const availability=ref<{available:boolean;reason:string}|null>(null),preparation=ref<ProjectDagCreationPreparation|null>(null),result=ref<ProjectDagCreationResult|null>(null);
const preview=computed(()=>preparation.value?.state==='preview'?preparation.value.preview:null);let disposed=false,epoch=0,returnFocus:HTMLElement|null=null;
const unsupported=computed(()=>!props.draft?'':props.draft.input.repositories.length!==1?'여러 저장소의 초안은 보존됩니다. 현재 DAG 규격은 단일 저장소만 지원해 생성할 수 없습니다.':props.draft.input.instructions.mode!=='custom'?'기존 지침의 자동 상속은 아직 검증되지 않았어요. 초안에서 직접 작성한 지침을 검토한 뒤 생성할 수 있습니다.':props.draft.input.instructions.additional.trim()?'추가 지침의 우선순위는 자동으로 정하지 않습니다. 직접 작성한 지침에 내용을 정리한 뒤 다시 검토하세요.':!props.draft.input.instructions.text.trim()?'초안에 직접 작성한 프로젝트 지침이 필요합니다.':'');
const reasons:Record<string,string>={single_repository_required:'현재 DAG 규격은 단일 저장소만 지원합니다. 여러 저장소 정보는 초안에 남아 있습니다.',custom_instructions_required:'직접 작성하고 확인한 프로젝트 지침이 필요합니다.',additional_instructions_unresolved:'추가 지침의 적용 순서를 확인해야 합니다. 직접 지침에 정리해 주세요.',source_changed:'저장소·브랜치·초안 또는 연결 상태가 바뀌었습니다. 현재 관측을 확인한 뒤 다시 검토해 주세요.',draft_changed:'초안이 변경되었습니다. 목록에서 새 초안을 다시 열어 주세요.',destination_changed:'선택한 디렉터리 또는 대상 파일 상태가 바뀌었습니다. 다시 선택해 주세요.',invalid_destination:'프로젝트 노트 경로와 일치하는 기존 디렉터리를 선택해 주세요. 기존 dag.yaml은 덮어쓰지 않습니다.',invalid_source:'프로젝트 경로·기준 브랜치·Git 저장소 정보를 검증하지 못했습니다. 외부 설정 include나 외부 Git object 저장소는 현재 지원하지 않습니다.',source_validation_unavailable:'관측한 기존 로컬 워크트리를 선택하고 저장한 뒤 소스를 연결해 주세요.',destination_selection_unavailable:'생성 위치 선택이 취소되었거나 사용할 수 없습니다.',cancelled:'생성 검토를 취소했습니다. 새 DAG는 만들지 않았습니다.',timeout:'검증 응답을 확인하지 못했습니다. 현재 파일과 연결 상태를 확인해 주세요.'};
watch(()=>props.draft?.id,async id=>{epoch++;if(!id)return;returnFocus=document.activeElement as HTMLElement;projectPath.value='';baseBranch.value=(props.draft?.input.repositories[0]?.workspace.branch??'').replace(/^refs\/heads\//,'');verification.value='';preparation.value=null;result.value=null;reviewed.value=false;error.value='';availability.value=null;const current=epoch;try{const value=await window.noteApp.getProjectCreationAvailability();if(!disposed&&current===epoch)availability.value=value;}catch{if(!disposed&&current===epoch)error.value='생성 환경을 확인하지 못했어요.';}},{immediate:true});
async function cancelPreview(){const old=preview.value;preparation.value=null;reviewed.value=false;if(old)await window.noteApp.cancelProjectCreation({previewId:old.previewId}).catch(()=>{});}
async function close(){if(busy.value)return;await cancelPreview();emit('close');void nextTick(()=>returnFocus?.isConnected&&returnFocus.focus({preventScroll:true}));}
async function prepare(){if(busy.value||!props.draft||unsupported.value)return;busy.value=true;error.value='';result.value=null;await cancelPreview();try{const response=await window.noteApp.prepareProjectCreation({draftId:props.draft.id,expectedDraftRevision:props.draft.revision,projectPath:projectPath.value.trim(),baseBranch:baseBranch.value.trim(),verification:verification.value.split('\n').map(s=>s.trim()).filter(Boolean)});if(disposed)return;preparation.value=response;if(response.state==='unavailable')error.value=reasons[response.reason]??'생성을 준비하지 못했습니다. 선택한 경로와 소스 상태를 확인해 주세요.';}catch{error.value='생성 입력 또는 현재 저장소 상태를 확인해 주세요. 초안은 보존됩니다.';}finally{busy.value=false;}}
async function confirm(){const proposal=preview.value;if(busy.value||!reviewed.value||!proposal)return;busy.value=true;error.value='';try{const response=await window.noteApp.confirmProjectCreation({previewId:proposal.previewId,expectedContentHash:proposal.contentHash});if(disposed)return;result.value=response;if(response.state==='unavailable'){error.value=response.outcome==='uncertain'?'파일 생성 결과를 확인하지 못했습니다. 선택한 경로의 dag.yaml을 먼저 확인해 주세요. 자동으로 다시 쓰지 않습니다.':reasons[response.reason]??'생성을 완료하지 못했어요. 기존 파일은 덮어쓰지 않습니다.';}else preparation.value=null;}catch{error.value='생성 결과를 확인하지 못했습니다. 대상 경로를 먼저 확인하고 자동 재시도하지 마세요.';}finally{busy.value=false;}}
onUnmounted(()=>{disposed=true;epoch++;void cancelPreview();});
</script>
<template>
 <Dialog :visible="!!draft" modal header="빈 DAG 생성 검토" :closable="false" :close-on-escape="!busy" @update:visible="value=>{if(!value)close()}" :style="{width:'min(760px,95vw)'}" @keydown.esc.prevent.stop="close">
  <div class="dag-creation" data-testid="project-dag-creation">
   <p>태스크 없이 지침과 저장소 정보만 담은 dag.yaml 한 파일을 만듭니다. 검증 명령은 기록만 합니다.</p>
   <p v-if="unsupported" class="notice warning">{{unsupported}}</p><p v-else-if="availability&&!availability.available" class="notice warning">{{availability.reason}}</p>
   <p v-if="error" role="alert" class="notice error">{{error}}</p>
   <section v-if="result&&(result.state==='created'||result.state==='already-created')" role="status"><h3>빈 DAG를 만들었어요</h3><p class="path">{{result.targetPath}}</p><p>계획 준비 중 · 태스크 미작성 · 앱 프로젝트 연결 전</p><p>초안과 파일 생성은 보존됩니다. 이 노트를 읽을 범위를 별도로 허용하고, 기존 노트 연결 검토를 거치면 프로젝트에서 확인할 수 있습니다. Orca 실행과 AI 실행은 진행하지 않았습니다.</p></section>
   <template v-else>
    <fieldset v-if="!preview" :disabled="busy||!!unsupported||!availability?.available"><label for="dag-project-path">프로젝트 노트 경로</label><input id="dag-project-path" v-model="projectPath" placeholder="owner/repository/project-name" maxlength="1024"/><p class="field-help">노트 내 논리 경로입니다. 선택할 디렉터리 끝부분이 이 경로와 같아야 합니다. 프로젝트 이름으로 자동 생성하지 않습니다.</p><label for="dag-base-branch">기준 브랜치</label><input id="dag-base-branch" v-model="baseBranch" maxlength="256"/><p class="field-help">실제 로컬 Git 브랜치가 존재하는지 확인합니다. 브랜치를 만들거나 전환하지 않습니다.</p><label for="dag-verification">검증 지침 · 한 줄에 하나</label><textarea id="dag-verification" v-model="verification" rows="4" placeholder="프로젝트에서 사용할 검증 명령 또는 확인 절차"/><p class="field-help">DAG에 기록만 하며 실행하지 않습니다.</p><p class="notice">다음 버튼은 현재 저장소를 검증하고 생성 위치 선택 창을 엽니다. 미리보기 확인 전에는 파일을 쓰지 않습니다.</p></fieldset>
    <section v-else class="dag-create-preview"><h3>이 파일만 생성합니다</h3><p class="path">{{preview.targetPath}}</p><p>기존 대상 없음 · {{preview.byteLength}} bytes · 태스크 0개 · 실행 라운드 0개</p><p class="hash">SHA-256: {{preview.contentHash}}</p><details open><summary>정확한 파일 내용</summary><pre>{{preview.content}}</pre></details><p>기존 파일을 덮어쓰지 않습니다. context.md, 워크트리, 노트 링크, 읽기 권한은 추가하지 않습니다.</p><label class="confirm"><input v-model="reviewed" type="checkbox" :disabled="busy"/> 대상 경로와 내용을 확인했으며 이 dag.yaml 한 파일 생성을 승인합니다</label></section>
   </template>
  </div>
  <template #footer><Button label="닫기" text :disabled="busy" @click="close"/><template v-if="(!result||result.state==='unavailable')&&!(result?.state==='unavailable'&&result.outcome==='uncertain')"><Button v-if="preview" label="입력 다시 검토" outlined :disabled="busy" @click="cancelPreview"/><Button v-if="preview" label="확인하고 빈 DAG 생성" :disabled="!reviewed" :loading="busy" data-testid="project-dag-confirm" @click="confirm"/><Button v-else label="생성 위치 선택 및 미리보기" :disabled="!!unsupported||!availability?.available" :loading="busy" data-testid="project-dag-prepare" @click="prepare"/></template></template>
 </Dialog>
</template>
<style scoped>
.dag-creation{line-height:1.7}.dag-creation fieldset{border:0;padding:0;margin:0;min-width:0}.dag-creation label{display:block;margin:16px 0 7px;font-weight:600}.dag-creation input:not([type=checkbox]),.dag-creation textarea{width:100%;box-sizing:border-box;padding:10px 12px;border:1px solid var(--app-control-border);border-radius:8px;background:var(--app-surface);color:inherit;font:inherit}.dag-creation textarea{resize:vertical}.field-help{font-size:.82rem;color:var(--app-text-muted);margin:6px 0 14px}.path,.hash{overflow-wrap:anywhere}.hash{font-size:.75rem}.dag-create-preview pre{white-space:pre-wrap;overflow-wrap:anywhere;background:var(--app-surface-muted);padding:14px;border-radius:8px;font-size:.8rem}.confirm{display:flex!important;align-items:flex-start;gap:9px}.confirm input{margin-top:7px}
</style>
