<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted,nextTick} from 'vue';
import Button from 'primevue/button';
import Dialog from 'primevue/dialog';
import type {ModelRetryProposal} from '../../shared/model-retry';
import type {ProjectModelView} from '../../main/project-model';
import {AI_TRANSFER_WARNING,PREFIX_AI_TRANSFER_WARNING} from '../../shared/ai-transfer';
const props=defineProps<{inlineControls?:boolean;summaryPrefix?:string;workstreamId:string;current:boolean;blockedReason?:string|null;workstreamTitle?:string;noteRootPath?:string}>();
const model=ref<ProjectModelView|null>(null),running=ref(false),confirmed=ref(false),error=ref('');let generation=0,disposed=false;
const controlsOpen=ref(false),consentTrigger=ref<HTMLButtonElement|null>(null);
function closeControls(){confirmed.value=false;void dismissRetry();void nextTick(()=>consentTrigger.value?.focus());}
const retryTicket=ref<ModelRetryProposal|null>(null),retryConfirmed=ref(false),preparingRetry=ref(false);
async function dismissRetry(){const t=retryTicket.value;retryTicket.value=null;retryConfirmed.value=false;if(t)await window.noteApp.cancelModelRetry({ticketId:t.ticketId}).catch(()=>{});}
async function prepareRetry(){if(running.value||preparingRetry.value||!confirmed.value||!props.current)return;preparingRetry.value=true;error.value='';try{const t=await window.noteApp.prepareModelRetry({workstreamId:props.workstreamId});if(disposed){await window.noteApp.cancelModelRetry({ticketId:t.ticketId});return;}retryTicket.value=t;}catch{error.value='동일한 실패 입력을 확인하지 못했거나 진단 재시도가 이미 사용되었습니다. 모델을 호출하지 않았습니다.';await load();}finally{preparingRetry.value=false;}}
async function retry(){const t=retryTicket.value;if(!t||!retryConfirmed.value||running.value||!props.current)return;retryTicket.value=null;retryConfirmed.value=false;const own=++generation;running.value=true;error.value='';try{const v=await window.noteApp.runModelRetry({ticketId:t.ticketId,transferConfirmed:true,oneCallConfirmed:true});if(!disposed&&own===generation)model.value=v;}catch{if(!disposed&&own===generation)error.value='진단 재시도 결과를 확인하지 못했습니다. 자동 재전송하지 않습니다.';}finally{if(own===generation)running.value=false;}}
const latest=computed(()=>model.value&&'latest' in model.value.latest?model.value.latest.latest:null);
const titles={implemented:'현재 어디까지 구현되었나요?',next:'다음에는 무엇을 구현하나요?',evidence:'완료 판단에 어떤 근거가 있나요?',decisions:'논의하거나 결정할 일이 있나요?'};
async function load(){const own=generation;try{const v=await window.noteApp.getProjectModelState({workstreamId:props.workstreamId});if(!disposed&&own===generation)model.value=v;}catch{error.value='저장 상태를 확인하지 못했습니다. 모델을 호출하지 않습니다.';}}
async function run(){if(running.value||!confirmed.value||!props.current)return;const own=++generation;running.value=true;error.value='';try{const v=await window.noteApp.summarizeProjectModel({workstreamId:props.workstreamId,transferConfirmed:true});if(!disposed&&own===generation)model.value=v;}catch{if(!disposed&&own===generation)error.value='전송·실행을 확인하지 못했습니다. 자동 재전송하지 않습니다.';}finally{if(own===generation)running.value=false;}}
async function cancel(){generation++;running.value=false;try{const v=await window.noteApp.cancelProjectModel({workstreamId:props.workstreamId});if(!disposed)model.value=v;}catch{}}
// 단순 관측시간 경과는 실행 중인 snapshot 요청을 취소하지 않습니다.
// 연결/권한/실제 근거 변경은 main이 검증하고 프로젝트 이동은 unmount가 취소합니다.
onMounted(load);onUnmounted(()=>{disposed=true;void dismissRetry();generation++;if(running.value)void window.noteApp.cancelProjectModel({workstreamId:props.workstreamId}).catch(()=>{});});
</script>
<template>
  <section class="public-model-review" data-testid="project-model-review">
    <div class="section-heading"><h3>{{summaryPrefix?summaryPrefix+' 접두사의':'이 프로젝트의'}} Claude AI 요약</h3><button v-if="!inlineControls" ref="consentTrigger" type="button" class="disclosure-button" data-testid="project-ai-open" aria-haspopup="dialog" :aria-expanded="controlsOpen" @click="controlsOpen=true">AI 요약 실행 설정</button></div>
    <component :is="inlineControls?'div':Dialog" v-model:visible="controlsOpen" :modal="!inlineControls" header="Claude AI 요약 · 전송 확인" :style="inlineControls?undefined:{width:'min(760px,94vw)'}" @hide="closeControls"><div class="info-dialog-body"><p v-if="workstreamTitle">대상 프로젝트: {{workstreamTitle}}</p><p v-if="noteRootPath">노트 범위: {{noteRootPath}}</p><p class="notice warning" data-testid="project-ai-warning">{{summaryPrefix?PREFIX_AI_TRANSFER_WARNING:AI_TRANSFER_WARNING}}</p>
    <label><input v-model="confirmed" type="checkbox" data-testid="project-ai-confirm"> 전송 대상과 자료 범위·민감정보 주의사항을 확인했습니다</label>
    <p v-if="summaryPrefix" class="muted">선택 접두사의 작업 최대 20개와 연결된 의존성 ID·상태만 AI 입력에 포함합니다. 접두사와 연결되지 않은 문서 본문은 제외합니다.</p><p class="muted">관련 근거를 한도 안에서 선별합니다. 동시 1개 · 생성 1회/형식 검증 실패 수정 최대 1회 · 일반 요약의 같은 입력 재호출 없음 · 실패 진단은 별도 확인 후 1회 · 선택 범위별 성공 본문 1개 보존</p>
    <Button label="지금 요약 · Claude AI" data-testid="project-ai-run" :disabled="running||!current||!confirmed||model?.state==='disabled'" :loading="running" @click="run"/><Button v-if="running" label="요약 취소" outlined data-testid="project-ai-cancel" @click="cancel"/>
    <Button v-if="model?.retry?.inputHash" label="실패 진단 재시도 · 1회" data-testid="project-ai-retry" outlined :disabled="running||preparingRetry||!current||!confirmed||!model.retry.available" :loading="preparingRetry" @click="prepareRetry"/>
    <p v-if="model?.retry?.used&&model.retry.inputHash" class="muted">이 실패 입력의 진단 재시도는 이미 예약·사용되었습니다. 재시작 후에도 추가 호출하지 않습니다.</p>
    <Dialog :visible="!!retryTicket" modal header="실패 진단 재시도 · 1회" :style="{width:'min(640px,90vw)',overflowWrap:'anywhere'}" @update:visible="value=>{if(!value)dismissRetry()}">
      <template v-if="retryTicket"><p>대상: {{workstreamTitle??'현재 선택한 이 프로젝트'}} · {{summaryPrefix?summaryPrefix+' 접두사 · ':''}}기존 로그인된 Claude</p><p v-if="noteRootPath">노트 디렉토리: {{noteRootPath}}</p><p>실패 입력 해시: {{retryTicket.inputHash}}</p><p>Claude 추가 호출 최대 1회 · 자동 형식 수정 0회 · 추가 재호출 0회. 기존 실패 ledger와 성공 요약을 보존하며 진단 응답으로 본문을 교체하지 않습니다.</p><p>현재 근거·권한과 동일 입력을 다시 확인합니다. 예약 후 취소·중단되어도 재시작으로 재호출할 수 없습니다. 원문·인증 정보는 진단 로그에 저장하지 않습니다.</p><label><input v-model="retryConfirmed" type="checkbox" data-testid="project-ai-retry-confirm"> 전송 범위와 Claude 추가 호출 1회 제한을 확인했습니다</label><Button label="취소" @click="dismissRetry"/><Button label="진단 1회 실행" data-testid="project-ai-retry-run" :disabled="!retryConfirmed||!current" @click="retry"/></template>
    </Dialog>
    </div></component>
    <Button v-if="running&&!controlsOpen&&!inlineControls" label="요약 취소" outlined data-testid="project-ai-cancel" @click="cancel"/>
    <p v-if="!current" class="notice warning">{{running?'진행 중인 요약은 시작 시점에 확인한 근거를 사용합니다. 연결·권한·실제 근거가 바뀌면 결과를 저장하지 않습니다.':blockedReason??'새 요약에 필요한 현재 소스 접근을 확인하지 못했습니다.'}}</p><p role="status">{{running?'현재 근거 검사·수동 요약 중입니다.':model?.message}}</p><p v-if="error" role="alert">{{error}}</p>
    <details v-if="model?.diagnostics" data-testid="project-model-diagnostics"><summary>요약 진단 기록 · {{model.diagnostics.records.length}}건</summary><p class="muted">원문·프롬프트·모델 출력·인증 정보는 저장하지 않습니다. 최대 {{model.diagnostics.retention.maxRecords}}건 · {{model.diagnostics.retention.days}}일, 기록 저장·조회 때 지난 기록을 정리합니다. 각 프로젝트의 최근 12건을 표시합니다.</p><p>macOS 확인 경로: ~/Library/Application Support/note-app/{{model.diagnostics.location}}</p><p v-if="!model.diagnostics.available" role="alert">진단 저장소를 확인하지 못했습니다. 새 모델 호출 전에 기록이 실패하면 실행을 중단합니다.</p><p v-if="!model.diagnostics.records.length">저장된 진단이 없습니다. 이 버전 이전의 실패 원인은 소급 기록하지 않습니다.</p><ul><li v-for="r in model.diagnostics.records" :key="r.correlationId+r.at+r.code"><time>{{r.at}}</time> · {{r.stage}} · <strong>{{r.code}}</strong> · 모델 {{r.modelCall}}<br>상관 ID {{r.correlationId}}<br>프로젝트 {{r.projectId}}<span v-if="r.attempt"> · 시도 {{r.attempt}}</span><p v-if="r.process">종료 {{r.process.exitCode??'미확인'}} · 신호 {{r.process.signal}} · {{r.process.durationMs}}ms · 응답 {{r.process.outputBytes}}bytes · 오류 출력 {{r.process.stderrBytes}}bytes · 정리 {{r.process.cleanup}}</p></li></ul><p class="muted">not-started=실행 전, launch-requested=실행 요청 기록(시작 확인 전), started=프로세스 시작 확인, unknown=확인 불가. 시작 확인은 응답 성공·과금 확정이 아닙니다. 마지막 기록 뒤 결과가 없으면 완료 여부를 알 수 없습니다.</p></details>
    <p :class="model?.latest.state==='stale'?'notice warning':'muted'">{{model?.latest.message}}</p>
    <template v-if="latest"><p v-if="latest.version==='connected-project-reading-v1'" class="notice warning">이전 입력 계약의 저장 결과입니다. 최근 작업 선별과 과거 승인 설명이 충분하지 않을 수 있어 현재 기준의 내용 검수가 필요합니다. 원문과 생성 시각은 보존했습니다.</p><p class="notice warning">{{latest.validation.note}}</p><p class="muted">{{latest.provider}} · 생성 {{latest.generatedAt}} · 생성 1회/검증 수정 {{latest.attempts-1}}회 · 문맥 검수 필요</p><section v-for="s in latest.answer.sections" :key="s.id"><h4>{{titles[s.id]}}</h4><p>{{s.text}}</p><small class="muted">근거 {{s.sourceIds.join(' · ')}}</small></section><details><summary>입력·보관 근거</summary><p>입력 해시 {{latest.inputHash}}</p><p>형식·필수 근거 검사는 문맥의 진실성이나 전체 개발 완료를 보장하지 않습니다. 실패·취소 시 이전 성공 결과를 보존합니다.</p><ul><li v-for="source in latest.sources" :key="source.id">{{source.id}} · {{source.path}}</li></ul></details></template>
  </section>
</template>
