<script setup lang="ts">
import {computed,nextTick,onMounted,onUnmounted,ref,toRaw,watch} from 'vue';
import type {ProjectWorkspaceOptions} from '../../shared/project-workspaces';
import ProjectDagCreation from './ProjectDagCreation.vue';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import {createEmptyProjectDraftInput,parseProjectDraftInput,type ProjectDraft,type ProjectDraftInput} from '../../shared/project-draft';
const emit=defineEmits<{draftCount:[number]}>();
const creationDraft=ref<ProjectDraft|null>(null);
const drafts=ref<ProjectDraft[]>([]),visible=ref(false),step=ref(0),busy=ref(false),loading=ref(true),listError=ref(''),error=ref(''),notice=ref(''),discarding=ref(false);
const input=ref<ProjectDraftInput>(createEmptyProjectDraftInput()),editing=ref<ProjectDraft|null>(null),initial=ref('');
const trigger=ref<HTMLElement|null>(null),form=ref<HTMLFormElement|null>(null);let disposed=false,returnFocus:HTMLElement|null=null;
watch(()=>drafts.value.length,count=>emit('draftCount',count),{immediate:true});
const dirty=computed(()=>JSON.stringify(input.value)!==initial.value);
const workspaceOptions=ref<ProjectWorkspaceOptions|null>(null),workspaceBusy=ref(false),workspaceMessage=ref('');
async function loadWorkspaces(){if(workspaceBusy.value)return;workspaceBusy.value=true;workspaceMessage.value='';try{workspaceOptions.value=await window.noteApp.getProjectWorkspaceOptions();}catch{workspaceMessage.value='Orca 작업 환경 목록을 확인하지 못했어요.';}finally{workspaceBusy.value=false;}}
watch([visible,step],([shown,current])=>{if(shown&&current===1)void loadWorkspaces();});
async function selectWorkspace(index:number,event:Event){const optionId=(event.target as HTMLSelectElement).value,option=workspaceOptions.value?.options.find(o=>o.optionId===optionId);if(!option)return;const owner=input.value,target=owner.repositories[index],before=JSON.stringify(target);workspaceBusy.value=true;workspaceMessage.value='';try{const selected=await window.noteApp.resolveProjectWorkspace({optionId,expectedFingerprint:option.fingerprint});if(disposed||!visible.value||input.value!==owner||!owner.repositories.includes(target)||JSON.stringify(target)!==before)return;const repository=target;if(!repository.name)repository.name=selected.repository.label;repository.path=selected.path;repository.workspace={mode:'existing',worktreeId:selected.worktreeId,path:selected.path,branch:selected.branch??''};workspaceMessage.value='현재 관측에서 선택한 작업 환경을 입력했어요. 저장은 연결 권한이나 실행을 부여하지 않습니다.';}catch{if(disposed||!visible.value||input.value!==owner)return;workspaceMessage.value='Orca 관측이 바뀌었어요. 목록을 다시 불러온 뒤 선택해 주세요.';}finally{workspaceBusy.value=false;(event.target as HTMLSelectElement).value='';}}
const stepTitles=['프로젝트 정보','지침과 작업 환경','저장 전 확인'];
const notion=computed({get:()=>input.value.references.find(r=>r.kind==='notion')?.url??'',set:value=>setSingle('notion',value)});
const slack=computed({get:()=>input.value.references.find(r=>r.kind==='slack')?.url??'',set:value=>setSingle('slack',value)});
const figma=computed(()=>input.value.references.filter(r=>r.kind==='figma'));
function setSingle(kind:'notion'|'slack',url:string){input.value.references=input.value.references.filter(r=>r.kind!==kind);if(url)input.value.references.push({kind,url,state:'entered'});}
async function load(){loading.value=true;listError.value='';try{const result=await window.noteApp.listProjectDrafts();if(!disposed)drafts.value=result;}catch{if(!disposed)listError.value='준비 중인 프로젝트를 불러오지 못했어요. 다시 시도해 주세요.';}finally{if(!disposed)loading.value=false;}}
onMounted(load);onUnmounted(()=>{disposed=true;});
function open(draft:ProjectDraft|null=null){if(busy.value)return;returnFocus=document.activeElement as HTMLElement;editing.value=draft;input.value=draft?parseProjectDraftInput(draft.input):createEmptyProjectDraftInput();initial.value=JSON.stringify(input.value);step.value=0;error.value='';notice.value='';discarding.value=false;visible.value=true;void nextTick(()=>document.getElementById('new-project-name')?.focus());}
function requestClose(){if(busy.value)return;if(dirty.value){discarding.value=true;return;}visible.value=false;error.value='';}
function restoreFocus(){void nextTick(()=>{if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else trigger.value?.focus({preventScroll:true});});}
function addRepository(){input.value.repositories.push({name:'',path:'',workspace:{mode:'existing',worktreeId:'',path:'',branch:''}});}
function focusError(){void nextTick(()=>{const container=form.value?.closest('.p-dialog-content');if(container)container.scrollTop=0;form.value?.querySelector<HTMLElement>('[role=alert]')?.focus({preventScroll:true});});}
function validate(){const counts={notion:0,slack:0,figma:0};for(const reference of input.value.references){counts[reference.kind]++;try{parseProjectDraftInput({...createEmptyProjectDraftInput(),references:[reference]});}catch{step.value=0;error.value=({notion:'Notion',slack:'Slack',figma:'Figma'}[reference.kind])+' 링크 '+counts[reference.kind]+'의 주소를 확인해 주세요. 해당 서비스의 https 링크만 저장할 수 있습니다.';focusError();return false;}}try{parseProjectDraftInput(toRaw(input.value));error.value='';return true;}catch(e){error.value=e instanceof Error?e.message:'입력한 항목을 확인해 주세요.';focusError();return false;}}
async function save(){if(busy.value||!validate())return;busy.value=true;error.value='';try{const saved=await window.noteApp.saveProjectDraft({id:editing.value?.id??null,expectedRevision:editing.value?.revision??null,input:parseProjectDraftInput(input.value)});if(disposed)return;drafts.value=[saved,...drafts.value.filter(d=>d.id!==saved.id)];editing.value=saved;initial.value=JSON.stringify(input.value);discarding.value=false;visible.value=false;notice.value='프로젝트 초안을 앱에 저장했어요. 다시 열어 이어서 준비할 수 있습니다.';}catch{error.value='저장하지 못했어요. 입력은 그대로 남아 있습니다. 다른 창에서 수정했다면 닫은 뒤 목록을 새로 불러와 주세요.';focusError();}finally{busy.value=false;}}
async function focusStep(){await nextTick();const container=form.value?.closest('.p-dialog-content');if(container)container.scrollTop=0;form.value?.querySelector<HTMLElement>('section:not([style*="display: none"]) h3')?.focus({preventScroll:true});}
async function advance(){if(!validate())return;step.value=Math.min(2,step.value+1);await focusStep();}
function back(){step.value=Math.max(0,step.value-1);error.value='';void focusStep();}
function addFigma(){input.value.references.push({kind:'figma',url:'',state:'entered'});}
function removeReference(reference:ProjectDraftInput['references'][number]){input.value.references=input.value.references.filter(r=>r!==reference);}
</script>
<template>
 <section class="project-onboarding" aria-labelledby="new-project-heading" data-testid="project-onboarding">
  <div class="project-draft-heading"><div><h2 id="new-project-heading">새 프로젝트 시작</h2><p class="muted">프로젝트 정보와 여러 저장소의 작업 환경을 먼저 정리하세요</p></div><button ref="trigger" class="new-project-button" data-testid="new-project" @click="open()">＋ 새 프로젝트</button></div>
  <p v-if="notice" role="status" class="notice">{{notice}}</p><button v-if="drafts.length" type="button" class="draft-refresh" :disabled="loading" @click="load">초안 목록 새로고침</button>
  <p v-if="listError&&!visible" role="alert">{{listError}} <button @click="load">다시 불러오기</button></p>
  <p v-if="loading" class="muted" role="status">저장한 초안 확인 중…</p>
  <ul v-else-if="drafts.length" class="project-draft-list" aria-label="준비 중인 프로젝트"><li v-for="draft in drafts" :key="draft.id"><button @click="open(draft)" :aria-label="(draft.input.name||'이름 없는 프로젝트')+' 초안 이어서 준비'"><span><strong>{{draft.input.name||'이름 없는 프로젝트'}}</strong><small>계획 준비 중 · 태스크 미작성</small></span><span>{{draft.input.repositories.length}}개 저장소 · 이어서 준비 →</span></button><button type="button" class="draft-create" @click="creationDraft=draft">빈 DAG 생성 검토</button></li></ul>
  <p v-else-if="!loading&&!listError" class="muted">아직 준비 중인 프로젝트가 없습니다. 이름만 입력하고 초안으로 저장해도 됩니다.</p>
 </section>
 <ProjectDagCreation :draft="creationDraft" @close="creationDraft=null"/>
 <Dialog v-model:visible="discarding" modal header="저장하지 않은 변경이 있어요" :closable="false" :close-on-escape="false" :style="{width:'min(480px,92vw)'}" @keydown.esc.prevent.stop="discarding=false"><p>계속 작성하거나 초안을 저장하세요. 변경을 버려도 마지막으로 저장한 초안은 그대로 남습니다.</p><p v-if="error" role="alert" class="notice error">{{error}}</p><template #footer><Button label="계속 작성" outlined :disabled="busy" @click="discarding=false"/><Button label="변경 버리고 닫기" text :disabled="busy" @click="discarding=false;visible=false;error=''"/><Button label="초안 저장 후 닫기" :loading="busy" @click="save"/></template></Dialog>
 <Dialog :visible="visible" modal header="새 프로젝트 준비" :closable="false" :close-on-escape="false" :style="{width:'min(780px,95vw)'}" class="project-setup-dialog" @keydown.esc.prevent.stop="requestClose" @hide="restoreFocus" @after-hide="restoreFocus">
  <form ref="form" class="project-setup-form" @submit.prevent="save">
   <ol class="setup-steps" aria-label="프로젝트 준비 단계"><li v-for="(title,index) in stepTitles" :key="title" :aria-current="step===index?'step':undefined" :class="{current:step===index}"><span>{{index+1}}</span>{{title}}</li></ol>

   <div v-if="error" role="alert" tabindex="-1" class="notice error">{{error}}</div>
   <fieldset :disabled="busy" class="setup-fields">
   <section v-show="step===0" aria-labelledby="setup-info-heading"><h3 id="setup-info-heading" tabindex="-1">어떤 프로젝트인가요?</h3>
    <label for="new-project-name">프로젝트 이름</label><input id="new-project-name" v-model="input.name" maxlength="160" autocomplete="off" placeholder="예: 팀 문서 검색 개선" data-testid="project-name"/>
    <label for="new-project-description">프로젝트 설명 <span class="muted">선택</span></label><textarea id="new-project-description" v-model="input.description" rows="5" maxlength="12000" placeholder="해결하려는 문제, 원하는 결과, 아직 결정하지 않은 점을 적어 주세요"/><p class="field-help">입력한 설명은 초안에 보관합니다. 나중에 파일 참조를 추가할 수 있도록 링크와 별도로 관리합니다.</p>
    <label for="new-project-notion">Notion 링크 <span class="muted">선택</span></label><input id="new-project-notion" v-model="notion" type="url" placeholder="https://www.notion.so/…"/>
    <label for="new-project-slack">Slack 링크 <span class="muted">선택</span></label><input id="new-project-slack" v-model="slack" type="url" placeholder="https://workspace.slack.com/archives/…"/>
    <div class="field-heading"><label>Figma 링크 <span class="muted">여러 개 가능</span></label><button type="button" :disabled="figma.length>=12" @click="addFigma">＋ Figma 링크 추가</button></div>
    <div v-for="(reference,index) in figma" :key="index" class="reference-row"><input v-model="reference.url" type="url" :aria-label="'Figma 링크 '+(index+1)" placeholder="https://www.figma.com/design/…"/><button type="button" :aria-label="'Figma 링크 '+(index+1)+' 제거'" @click="removeReference(reference)">제거</button></div>
    <p class="field-help">링크는 입력한 주소만 저장합니다. 내용 확인·다운로드·AI 전송은 실행하지 않습니다.</p>
   </section>
   <section v-show="step===1" aria-labelledby="setup-environment-heading"><h3 id="setup-environment-heading" tabindex="-1">지침과 작업 환경</h3>
    <label for="new-project-note">기준 노트 / DAG 위치</label><input id="new-project-note" v-model="input.noteLocation" placeholder="프로젝트의 기준 노트 폴더 또는 DAG 경로"/><p class="field-help">아래 저장소와 별개인 기준 위치입니다. 경로는 기록만 하며, 파일을 읽거나 만들지 않습니다.</p>
    <label for="new-project-instructions-mode">프로젝트 지침</label><select id="new-project-instructions-mode" v-model="input.instructions.mode"><option value="inherit">기존 DAG 지침을 기준으로 준비</option><option value="custom">직접 지침 작성</option></select>
    <template v-if="input.instructions.mode==='inherit'"><label for="new-project-instructions-source">기존 지침 출처</label><input id="new-project-instructions-source" v-model="input.instructions.source" placeholder="참조한 DAG / 문서 위치"/><label for="new-project-instructions-revision">출처 버전 또는 해시 <span class="muted">알고 있다면 입력</span></label><input id="new-project-instructions-revision" v-model="input.instructions.sourceRevision" placeholder="직접 확인한 revision / hash"/><p class="field-help">출처를 자동으로 읽거나 최신 버전으로 바꾸지 않습니다. 아래에 확인한 지침을 붙여 넣어 보관하세요.</p></template>
    <label for="new-project-instructions">{{input.instructions.mode==='inherit'?'보관할 기존 지침 사본':'직접 작성한 지침'}}</label><textarea id="new-project-instructions" v-model="input.instructions.text" rows="4" maxlength="16000" placeholder="기준 브랜치, 검증 방법, 변경하면 안 되는 전제 등"/>
    <label for="new-project-additional">추가 지침 <span class="muted">선택</span></label><textarea id="new-project-additional" v-model="input.instructions.additional" rows="3" maxlength="8000"/>
    <div class="field-heading"><h4>참여 저장소</h4><button type="button" :disabled="input.repositories.length>=12" @click="addRepository">＋ 저장소 추가</button></div><p class="field-help">한 프로젝트의 여러 저장소별로 작업 환경을 기록합니다. 현재 관측한 기존 Orca 워크트리도 선택할 수 있습니다.</p><div class="workspace-options-status"><button type="button" :disabled="workspaceBusy" @click="loadWorkspaces">{{workspaceBusy?'목록 확인 중…':'Orca 작업 환경 목록 새로 확인'}}</button><p v-if="workspaceOptions?.state==='unavailable'" class="field-help">관측한 작업 환경이 없어요. 아래에 기존 워크트리 계획을 직접 적어 초안으로 보관하거나, 연결 및 설정에서 소스를 연결한 뒤 다시 선택하세요. 직접 입력한 값은 연결 확인을 뜻하지 않습니다.</p><p v-if="workspaceOptions?.state==='ready'&&!workspaceOptions.options.length" class="field-help">현재 관측에서 선택 가능한 로컬 워크트리가 없습니다.</p><p v-if="workspaceMessage" role="status" class="field-help">{{workspaceMessage}}</p></div>
    <section v-for="(repository,index) in input.repositories" :key="index" class="setup-repository" :aria-label="'저장소 '+(index+1)"><div class="field-heading"><h4>저장소 {{index+1}}</h4><button type="button" :aria-label="'저장소 '+(index+1)+' 제거'" @click="input.repositories.splice(index,1)">제거</button></div>
     <label :for="'repo-name-'+index">저장소 이름</label><input :id="'repo-name-'+index" v-model="repository.name" placeholder="예: frontend"/>
     <label :for="'repo-path-'+index">저장소 위치</label><input :id="'repo-path-'+index" v-model="repository.path" placeholder="로컬 저장소 경로"/>
     <label :for="'repo-mode-'+index">작업 환경 계획</label><select :id="'repo-mode-'+index" v-model="repository.workspace.mode"><option value="existing">기존 Orca 워크트리 사용 예정</option><option value="new">새 워크트리 필요</option></select>
     <template v-if="repository.workspace.mode==='existing'"><label :for="'repo-observed-'+index">관측한 Orca 작업 환경에서 선택</label><select :id="'repo-observed-'+index" :disabled="workspaceBusy||!workspaceOptions?.options.length" @change="selectWorkspace(index,$event)"><option value="">현재 관측에서 선택…</option><option v-for="option in workspaceOptions?.options??[]" :key="option.optionId" :value="option.optionId">{{option.repository.label}} · {{option.branch||'브랜치 미확인'}} · {{option.path}}</option></select><p class="field-help">선택 시 현재 관측을 다시 검사하고 저장소·작업 경로를 이 체크아웃으로 채웁니다. 파일 접근·Git 검증은 생성 검토 단계에서 별도로 확인합니다.</p><label :for="'repo-tree-'+index">기존 워크트리 식별자 <span class="muted">알고 있다면 입력</span></label><input :id="'repo-tree-'+index" v-model="repository.workspace.worktreeId"/><label :for="'repo-workspace-'+index">작업 경로</label><input :id="'repo-workspace-'+index" v-model="repository.workspace.path"/></template>
     <label :for="'repo-branch-'+index">{{repository.workspace.mode==='new'?'기준 브랜치 계획':'브랜치'}}</label><input :id="'repo-branch-'+index" v-model="repository.workspace.branch" placeholder="예: develop"/>
     <p v-if="repository.workspace.mode==='new'" class="field-help">신규 생성은 준비 중입니다. Orca 생성 시 자동 터미널 명령이 실행될 수 있어 앱에서 생성하지 않습니다.</p>
    </section>
   </section>
   <section v-show="step===2" aria-labelledby="setup-review-heading"><h3 id="setup-review-heading" tabindex="-1">초안을 저장하고 이어서 준비하세요</h3><dl class="setup-review"><dt>프로젝트</dt><dd>{{input.name||'이름 미입력'}}</dd><dt>외부 참고 링크</dt><dd>{{input.references.filter(r=>r.url).length}}개 · 내용 미확인</dd><dt>기준 노트 / DAG</dt><dd>{{input.noteLocation||'위치 미입력'}}</dd><dt>지침</dt><dd>{{input.instructions.mode==='inherit'?'기존 지침 사본 보관':'직접 작성'}} · {{input.instructions.text?'입력됨':'미입력'}}</dd><dt>참여 저장소</dt><dd>{{input.repositories.length}}개 · 연결 미검증</dd></dl>
    <details class="setup-input-review"><summary>입력 내용 자세히 확인</summary><h4>설명</h4><p class="preserve-lines">{{input.description||'미입력'}}</p><h4>참고 링크 · 내용 미확인</h4><ul><li v-for="(reference,index) in input.references" :key="index">{{reference.kind}}: {{reference.url||'주소 미입력'}}</li></ul><h4>지침 사본</h4><p v-if="input.instructions.mode==='inherit'">출처: {{input.instructions.source||'미입력'}} · 버전: {{input.instructions.sourceRevision||'미입력'}}</p><p class="preserve-lines">{{input.instructions.text||'미입력'}}</p><p v-if="input.instructions.additional" class="preserve-lines">추가 지침: {{input.instructions.additional}}</p><h4>저장소별 작업 환경</h4><ul><li v-for="(repository,index) in input.repositories" :key="index"><strong>{{repository.name||'이름 미입력'}}</strong><br>저장소: {{repository.path||'미입력'}}<br>{{repository.workspace.mode==='existing'?'기존 워크트리':'새 워크트리 필요'}} · {{repository.workspace.worktreeId||'식별자 미입력'}}<br>작업 경로: {{repository.workspace.path||'미입력'}}<br>브랜치: {{repository.workspace.branch||'미입력'}}</li></ul></details>
    <p class="notice">계획 준비 중 · 태스크 미작성<br>저장하면 앱 안에 초안만 보관합니다. 이후 요구사항 수집과 계획 검토를 거쳐 태스크를 작성합니다.</p>
    <details class="setup-next"><summary>저장한 다음에는?</summary><ul><li>목록에서 초안을 다시 열어 정보와 저장소별 작업 환경을 수정할 수 있어요</li><li>저장소가 하나이고 직접 지침을 작성했다면, 목록의 ‘빈 DAG 생성 검토’에서 실제 파일 생성을 검토할 수 있어요</li><li>여러 저장소의 DAG 생성과 새 Orca 워크트리 생성은 아직 지원하지 않아요. 입력한 계획은 초안에 남습니다</li><li>참고 링크의 내용 수집과 AI 계획 작성은 별도로 진행해야 해요</li></ul><p>Orca에서 파일 화면을 여는 것과 AI 모델을 실행하는 것은 별도입니다. 초안 저장으로 어느 쪽도 실행하지 않습니다.</p></details>
   </section>
   </fieldset>
  </form>
  <template #footer><div class="setup-footer"><Button label="닫기" text :disabled="busy" @click="requestClose"/><span class="setup-footer-spacer"/><Button v-if="step>0" label="이전" outlined :disabled="busy" @click="back"/><Button v-if="step<2" label="다음" outlined :disabled="busy" @click="advance"/><Button label="초안 저장" :loading="busy" :disabled="loading" data-testid="project-draft-save" @click="save"/></div></template>
 </Dialog>
</template>
<style scoped>
.project-onboarding{border:1px solid var(--app-border);border-radius:14px;padding:20px;margin:0 0 24px;background:var(--app-surface)}
.draft-refresh{margin-top:14px;background:transparent;border:1px solid var(--app-control-border);color:inherit;padding:6px 9px;border-radius:7px;cursor:pointer}.project-draft-heading,.field-heading{display:flex;align-items:center;justify-content:space-between;gap:12px}.project-draft-heading h2{margin:0;font-size:1.1rem}.project-draft-heading p{margin:7px 0 0}.new-project-button{white-space:nowrap;background:var(--app-primary);color:var(--app-on-primary);border:0;border-radius:9px;padding:11px 16px;font-weight:650;cursor:pointer}.project-draft-list{list-style:none;margin:18px 0 0;padding:0}.project-draft-list .draft-create{width:auto;border:1px solid var(--app-control-border);border-radius:7px;padding:6px 10px;margin-bottom:12px;font-size:.8rem}.project-draft-list li+li{border-top:1px solid var(--app-border)}.project-draft-list button{display:flex;justify-content:space-between;align-items:center;gap:16px;width:100%;border:0;background:transparent;color:inherit;text-align:left;padding:15px 0;cursor:pointer}.project-draft-list small{display:block;margin-top:5px;font-size:.8rem;color:var(--app-text-muted)}
.setup-steps{display:flex;gap:14px;list-style:none;padding:0;margin:0 0 24px;color:var(--app-text-muted);font-size:.85rem}.setup-steps li{display:flex;align-items:center;gap:6px}.setup-steps span{border:1px solid currentColor;border-radius:50%;width:24px;height:24px;display:grid;place-items:center}.setup-steps .current{font-weight:700;color:var(--app-text)}.setup-fields{padding:0;margin:0;border:0;min-width:0}.setup-fields h3{font-size:1.15rem;margin:0 0 20px}.setup-fields label{display:block;font-weight:600;font-size:.9rem;margin:17px 0 7px}.setup-fields input,.setup-fields textarea,.setup-fields select{display:block;width:100%;box-sizing:border-box;background:var(--app-surface);color:inherit;border:1px solid var(--app-control-border);border-radius:8px;padding:10px 12px;font:inherit}.setup-fields textarea{resize:vertical;min-height:80px}.field-help{font-size:.82rem;line-height:1.65;color:var(--app-text-muted);margin:7px 0 14px}.field-heading{margin-top:18px}.field-heading label,.field-heading h4{margin:0}.field-heading button,.reference-row button,.setup-repository button{background:transparent;color:inherit;border:1px solid var(--app-control-border);border-radius:7px;padding:7px 10px;font:inherit;font-size:.85rem;cursor:pointer}.reference-row{display:flex;gap:8px;margin-top:8px}.reference-row input{min-width:0}.reference-row button{flex-shrink:0}.setup-repository{border:1px solid var(--app-border);padding:16px;border-radius:12px;margin-top:14px}.setup-repository>.field-heading{margin-top:0}.setup-review{display:grid;grid-template-columns:140px minmax(0,1fr);gap:12px 18px}.setup-review dt{color:var(--app-text-muted)}.setup-review dd{margin:0;overflow-wrap:anywhere}.setup-input-review{line-height:1.7;overflow-wrap:anywhere;margin:20px 0}.setup-input-review summary{cursor:pointer;font-weight:650}.setup-input-review li{margin-bottom:12px}.preserve-lines{white-space:pre-wrap}.setup-next{line-height:1.7;margin-top:20px}.setup-next summary{cursor:pointer;font-weight:650}.setup-next ul{padding-left:22px}.setup-footer{display:flex;align-items:center;gap:9px;width:100%;flex-wrap:wrap}.setup-footer-spacer{flex:1}.setup-discard{margin-bottom:18px}.project-setup-form{max-width:100%}.project-setup-form button:focus-visible,.new-project-button:focus-visible,.project-draft-list button:focus-visible{outline:3px solid var(--app-primary);outline-offset:3px}
@media(max-width:600px){.project-draft-heading,.project-draft-list button{align-items:flex-start;flex-direction:column}.setup-steps{gap:7px;font-size:.72rem}.setup-steps span{width:20px;height:20px}.setup-review{grid-template-columns:1fr;gap:4px}.setup-review dd{margin-bottom:10px}}
</style>
