<script setup lang="ts">
import {computed,ref} from 'vue';
import type {LiveWorkstreamView,LiveDagView} from '../../shared/live';
import {projectResources} from '../../phase2/resources';
import {evaluateDispatchRecommendation,type DispatchReviewSignal} from '../../phase2/recommendations';
import {interpretTasks} from '../../phase2/tasks';
import {liveState} from '../store';
const props=defineProps<{workstream:LiveWorkstreamView;dag?:LiveDagView}>();
const acknowledged=ref(false);
const resources=computed(()=>projectResources({workstreams:liveState.value?.workstreams??[],codeburn:liveState.value?.codeburn.results??[],observedAt:liveState.value?.observedAt??null,freshness:liveState.value?.freshness??'unknown',coverage:liveState.value?.coverage??null}));
const rows=computed(()=>interpretTasks(props.dag?.workspaceTasks??props.dag?.tasks??[],{projectId:props.workstream.id,dagId:props.dag?.dagId??'',sourceHash:props.dag?.sourceHash??'',observedAt:props.dag?.observedAt??'',policies:props.dag?.policies??[]}));
const reviewSignals=computed<DispatchReviewSignal[]>(()=>rows.value.flatMap(row=>{const kind=row.verification?'verification':row.discussion?'discussion':row.review?'review':null;return kind?[{id:row.task.id,kind,state:'pending' as const,source:'dag-declaration:'+props.dag?.dagId,observedAt:props.dag?.observedAt?Date.parse(props.dag.observedAt):null,freshness:liveState.value?.freshness??'unknown',reason:'정책 해석 또는 필수 근거 선언을 확인할 작업입니다. 실제 검증 통과를 뜻하지 않습니다.'}]:[]}));
const advisory=computed(()=>evaluateDispatchRecommendation({quota:resources.value.quota,memory:resources.value.memory,reviewSignals:reviewSignals.value,acknowledged:acknowledged.value}));
const unregistered=computed(()=>resources.value.workstreams.filter(w=>w.tier!=='registered-project'));
const time=(value:number|null)=>value===null?'미확인':new Date(value).toLocaleString();
</script>
<template>
 <section data-testid="resource-workspace"><h2>사용량과 관측 범위</h2><p>{{workstream.title}}의 프로젝트 소비량과 전체 제공자·계정 한도는 서로 다른 관측입니다.</p>
  <div class="resource-grid"><article class="resource-card"><h3>프로젝트 토큰</h3><strong>미확인</strong><p>현재 수집기는 저장소별 토큰·역사 기간을 제공하지 않습니다. 0으로 표시하거나 계정 한도에서 환산하지 않습니다.</p></article><article class="resource-card"><h3>현재 프로젝트 메모리</h3><strong>수집 미지원</strong><p>Orca 세션의 PID·시작 시각·RSS 연결을 확인하지 못했습니다. Mac 메모리 압력·swap도 미관측입니다.</p></article></div>
  <h3>계정별 한도</h3><p class="notice warning">조회 계정 식별 미확인 · 전체 계정 관측 미확인. 현재 연동은 provider별 한 행이며, Codex·Claude 복수 계정 수집은 지원되지 않습니다.</p>
  <div class="resource-grid"><template v-for="provider in resources.quota.providers" :key="provider.provider"><article v-for="account in provider.accounts" :key="account.accountRef" class="resource-card"><h4>{{provider.provider}} · {{account.identity==='legacy-account-unknown'?'조회 계정 미확인':account.accountRef}}</h4><p>{{account.freshness}} · {{account.quotaData}} · {{account.error??'오류 보고 없음'}}</p><div v-for="window in account.windows" :key="window.windowRef"><label>{{window.label}} · {{window.usedPct===null?'미확인':window.usedPct+'%'}}</label><meter v-if="window.usedPct!==null&&account.freshness==='current'" :value="Math.min(100,window.usedPct)" min="0" max="100" :aria-label="window.label+' 관측 사용률'"/><p>리셋 {{window.resetsAt??'미확인'}} · 시각 형식 {{window.resetTimeFormat}}</p></div><p v-if="!account.windows.length">관측한 한도 구간 없음</p><small>관측 {{time(account.observedAt)}}<br>마지막 성공 {{time(account.lastSuccess)}} · 마지막 시도 {{time(account.lastAttemptAt)}}<br>출처 {{account.source}} · 범위 {{account.coverage}}</small></article><p v-if="!provider.accounts.length">{{provider.provider}} 계정 한도 미관측</p></template></div><p>계정 간 퍼센트는 합산·평균하지 않습니다. 그래프는 현재 관측된 개별 구간만 표시하며 시계열을 만들어 내지 않습니다.</p>
  <h3>제공자 전체 역사 소비량</h3><p>CodeBurn의 추정 집계입니다. 이 프로젝트 비용이나 실제 청구액이 아닙니다. 오늘/월의 정확한 경계·시간대는 미확인입니다.</p>
  <table class="resource-table"><thead><tr><th>제공자·기간</th><th>관측 비용</th><th>호출</th><th>현재성·출처</th></tr></thead><tbody><tr v-for="(period,i) in resources.usage.providerPeriods" :key="i"><td>{{period.provider}} · {{period.period}}</td><td>{{period.cost??'미확인'}} {{period.currency}}</td><td>{{period.calls??'미확인'}}</td><td>{{period.freshness}} · {{time(period.observedAt)}} · {{period.source}}</td></tr></tbody></table><p v-if="!resources.usage.providerPeriods.length">역사 소비량 자료 미관측</p>
  <ul><li v-for="observation in resources.usage.providerObservations" :key="observation.provider">{{observation.provider}} · {{observation.state}} · {{observation.error??'오류 보고 없음'}} · 마지막 시도 {{time(observation.lastAttemptAt)}} · 마지막 성공 {{time(observation.lastSuccess)}}</li></ul><h3>프로젝트 미등록 작업 · 저장소별</h3><p>DAG 태스크 연결 여부는 프로젝트 등록과 별개입니다. 태스크 ID가 없는 응답만으로 미등재라고 단정하지 않습니다.</p><div class="resource-grid"><article v-for="row in unregistered" :key="row.workstreamId" class="resource-card"><h4>{{row.title}}</h4><p>{{row.tier==='repository-unregistered'?'저장소 확인 · 프로젝트 미등록':'저장소 미확인'}}</p><pre class="evidence-text">{{JSON.stringify({repository:row.repository,taskLinkage:row.taskLinkage},null,2)}}</pre><p>역사 소비량·현재 메모리 미확인</p></article></div><p v-if="!unregistered.length">현재 관측 범위에서 미등록 작업이 없습니다. 관측 범위 밖의 작업은 확인되지 않았습니다.</p>
  <section class="resource-card" data-testid="dispatch-advisory"><h3>추가 파견 판단 참고</h3><strong>{{advisory.state==='hold-advised'?'보류 검토 권고':advisory.state==='insufficient-observation'?'판단 근거 부족':'관측한 보류 사유 없음'}}</strong><p>실행 허가나 강제 차단이 아닙니다. 실제 실행은 Orca에서 판단합니다. unknown·오래된 자료를 실행 가능으로 바꾸지 않습니다.</p><ul><li v-for="(reason,i) in advisory.reasons.slice(0,20)" :key="i">{{reason.detail}} · {{reason.source}} · {{time(reason.observedAt)}}</li></ul><p v-if="advisory.reasons.length>20">추가 사유 {{advisory.reasons.length-20}}개 표시 생략</p><label><input v-model="acknowledged" type="checkbox"> 권고를 읽었습니다 (실행 제어 없음)</label><p class="muted">정책 {{advisory.policy.id}} v{{advisory.policy.version}} · 기존 관측의 화면 계산만 수행</p></section>
  <details><summary>수집 capability와 남은 검증</summary><pre class="evidence-text">{{JSON.stringify(resources.capabilities,null,2)}}</pre><p>공식 계정별 수집·실제 Mac 메모리 연계·저장소별 branch 수집은 별도 확인이 필요합니다. private cache·인증 정보는 조회하지 않습니다.</p></details>
 </section>
</template>
