<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted} from 'vue';
import type {AppMemoryView} from '../../shared/app-memory';
import Button from 'primevue/button';
import Select from 'primevue/select';
import type {LiveWorkstreamView,LiveDagView} from '../../shared/live';
import {projectResources} from '../../phase2/resources';
import {evaluateDispatchRecommendation,type DispatchReviewSignal} from '../../phase2/recommendations';
import {interpretTasks} from '../../phase2/tasks';
import {liveState} from '../store';
const props=defineProps<{workstream:LiveWorkstreamView;dag?:LiveDagView}>();
const acknowledged=ref(false),appMemory=ref<AppMemoryView|null>(null),memoryBusy=ref(false);let memoryTimer:ReturnType<typeof setInterval>|undefined,disposed=false;
async function refreshAppMemory(){if(memoryBusy.value||disposed)return;memoryBusy.value=true;try{const next=await window.noteApp.getAppMemory();if(!disposed)appMemory.value=next;}catch{if(!disposed)appMemory.value=null;}finally{memoryBusy.value=false;}}
onMounted(()=>{void refreshAppMemory();memoryTimer=setInterval(()=>{if(document.visibilityState==='visible'&&document.hasFocus())void refreshAppMemory();},15000);});onUnmounted(()=>{disposed=true;if(memoryTimer)clearInterval(memoryTimer);});
const usagePeriod=ref<'today'|'month'>('today');
const repositoryUsage=computed(()=>liveState.value?.repositoryUsage?.views.find(view=>view.query===usagePeriod.value)??null);
const linkedUsage=computed(()=>repositoryUsage.value?.projects.filter(project=>project.match.workstreamIds.includes(props.workstream.id)||project.branches.some(branch=>branch.sessionRows.some(session=>session.match.workstreamIds.includes(props.workstream.id))))??[]);
const otherRepositoryUsage=computed(()=>repositoryUsage.value?.projects.filter(project=>project.match.tier!=='registered-project')??[]);
const maxRepositoryCost=computed(()=>Math.max(0,...(repositoryUsage.value?.projects.map(project=>project.chartCost??0)??[])));
const resources=computed(()=>{const result=projectResources({workstreams:liveState.value?.workstreams??[],codeburn:liveState.value?.codeburn.results??[],observedAt:liveState.value?.observedAt??null,freshness:liveState.value?.freshness??'unknown',coverage:liveState.value?.coverage??null});if(liveState.value?.repositoryUsage?.capability==='configured')result.capabilities.repositoryUsage={state:'supported',reason:'공식 branch-json 고정 수집기 연결됨. 실제 조회 성공·자료 범위는 저장소 관측의 state/freshness/coverage를 별도로 확인합니다.'};return result;});
const rows=computed(()=>interpretTasks(props.dag?.workspaceTasks??props.dag?.tasks??[],{projectId:props.workstream.id,dagId:props.dag?.dagId??'',sourceHash:props.dag?.sourceHash??'',observedAt:props.dag?.observedAt??'',policies:props.dag?.policies??[]}));
const reviewSignals=computed<DispatchReviewSignal[]>(()=>rows.value.flatMap(row=>{const kind=row.verification?'verification':row.discussion?'discussion':row.review?'review':null;return kind?[{id:row.task.id,kind,state:'pending' as const,source:'dag-declaration:'+props.dag?.dagId,observedAt:props.dag?.observedAt?Date.parse(props.dag.observedAt):null,freshness:liveState.value?.freshness??'unknown',reason:'정책 해석 또는 필수 근거 선언을 확인할 작업입니다. 실제 검증 통과를 뜻하지 않습니다.'}]:[]}));
const advisory=computed(()=>evaluateDispatchRecommendation({quota:resources.value.quota,memory:resources.value.memory,reviewSignals:reviewSignals.value,acknowledged:acknowledged.value}));
const unregistered=computed(()=>resources.value.workstreams.filter(w=>w.tier!=='registered-project'));
const time=(value:number|null)=>value===null?'미확인':new Date(value).toLocaleString();
</script>
<template>
 <section data-testid="resource-workspace"><h2>사용량과 관측 범위</h2><p>{{workstream.title}}의 프로젝트 소비량과 전체 제공자·계정 한도는 서로 다른 관측입니다.</p>
  <div class="resource-grid"><article class="resource-card"><h3>연결된 저장소의 관측 토큰</h3><template v-for="project in linkedUsage" :key="project.codeburnProjectId"><strong>{{project.label}}</strong><p v-if="project.match.state==='matched'&&project.tokens">입력 {{project.tokens.inputTokens}} · 출력 {{project.tokens.outputTokens}} · 추론 {{project.tokens.reasoningTokens}}<br>캐시 읽기 {{project.tokens.cacheReadTokens}} · 쓰기 {{project.tokens.cacheWriteTokens}}</p><p v-else>전체 토큰 미확인 · 일부 세션의 연결/브랜치 정보만 관측했을 수 있습니다</p></template><strong v-if="!linkedUsage.length">귀속 미확인</strong><p>선택한 역사 기간의 기록입니다. 누락은0이 아니며 계정 한도에서 환산하지 않습니다.</p></article><article class="resource-card"><h3>현재 프로젝트 메모리</h3><strong>수집 미지원</strong><p>명시 PID용 Linux/Mac 관측기는 구현됐지만 현재 Orca 세션이 검증된 PID·시작 시각·worktree 연결을 제공하지 않아 프로젝트 조회는 하지 않습니다. 시스템 압력·swap도 미관측입니다.</p></article></div>
  <section class="resource-card" data-testid="app-memory"><div class="section-heading"><h3>note-app 자체 메모리</h3><Button label="앱 메모리 새로고침" text :loading="memoryBusy" @click="refreshAppMemory"/></div><p>{{appMemory?.reason??'앱 메모리 미관측'}}</p><p v-if="appMemory">{{appMemory.platform}} · {{appMemory.observedAt??'시각 미확인'}} · 화면 활성 중15초 간격, 배경에서는 추가 조회하지 않음</p><table v-if="appMemory?.rows.length" class="resource-table"><thead><tr><th>앱 프로세스</th><th>현재 working set</th><th>peak</th></tr></thead><tbody><tr v-for="row in appMemory.rows" :key="row.pid+':'+row.creationTime"><td>{{row.type}} · PID {{row.pid}}</td><td>{{row.workingSetKB===null?'미확인':row.workingSetKB.toLocaleString()+' KB'}}</td><td>{{row.peakWorkingSetKB===null?'미확인':row.peakWorkingSetKB.toLocaleString()+' KB'}}</td></tr></tbody></table><p v-if="appMemory?.omitted">미확인/상한으로 생략 {{appMemory.omitted}}개</p></section>
  <h3>계정별 한도</h3><p class="notice warning">조회 계정 식별 미확인 · 전체 계정 관측 미확인. 현재 연동은 provider별 한 행이며, Codex·Claude 복수 계정 수집은 지원되지 않습니다.</p>
  <div class="resource-grid"><template v-for="provider in resources.quota.providers" :key="provider.provider"><article v-for="account in provider.accounts" :key="account.accountRef" class="resource-card"><h4>{{provider.provider}} · {{account.identity==='legacy-account-unknown'?'조회 계정 미확인':account.accountRef}}</h4><p>{{account.freshness}} · {{account.quotaData}} · {{account.error??'오류 보고 없음'}}</p><div v-for="window in account.windows" :key="window.windowRef"><label>{{window.label}} · {{window.usedPct===null?'미확인':window.usedPct+'%'}}</label><meter v-if="window.usedPct!==null&&account.freshness==='current'" :value="Math.min(100,window.usedPct)" min="0" max="100" :aria-label="window.label+' 관측 사용률'"/><p>리셋 {{window.resetsAt??'미확인'}} · 시각 형식 {{window.resetTimeFormat}}</p></div><p v-if="!account.windows.length">관측한 한도 구간 없음</p><small>관측 {{time(account.observedAt)}}<br>마지막 성공 {{time(account.lastSuccess)}} · 마지막 시도 {{time(account.lastAttemptAt)}}<br>출처 {{account.source}} · 범위 {{account.coverage}}</small></article><p v-if="!provider.accounts.length">{{provider.provider}} 계정 한도 미관측</p></template></div><p>계정 간 퍼센트는 합산·평균하지 않습니다. 그래프는 현재 관측된 개별 구간만 표시하며 시계열을 만들어 내지 않습니다.</p>
  <section data-testid="repository-usage"><div class="section-heading"><h3>저장소별 역사 소비량</h3><label>관측 기간<Select v-model="usagePeriod" :options="[{value:'today',label:'오늘'},{value:'month',label:'이번 달'}]" option-label="label" option-value="value" aria-label="저장소 사용량 기간"/></label></div>
   <p>공식 CodeBurn branch-json의 읽기 전용 관측입니다. 같은 호스트에서 이미 관측한 checkout 경로가 정확히 일치할 때만 연결합니다. remote 이름으로 합치거나 외부 폴더를 찾지 않습니다. 경로 재사용 등 과거의 저장소 소유권까지 증명하지는 않습니다.</p>
   <p v-if="repositoryUsage">{{repositoryUsage.state}} · {{repositoryUsage.freshness}} · {{repositoryUsage.error??'오류 보고 없음'}} · 마지막 성공 {{time(repositoryUsage.lastSuccess)}} · 마지막 시도 {{time(repositoryUsage.lastAttemptAt)}}</p><p v-if="repositoryUsage?.period">{{repositoryUsage.period.label}}: {{repositoryUsage.period.start}} ~ {{repositoryUsage.period.end}} (끝 포함, 수집기 로컬 시간대 미확인)</p><p>현재 조회 비용 {{liveState?.repositoryUsage?.durationMs??'미확인'}}ms · 정기 최소 간격 {{(liveState?.repositoryUsage?.minimumIntervalMs??60000)/1000}}초 · 전체 새로고침은 수동 재조회</p>
   <p v-if="!repositoryUsage?.projects.length">확인된 저장소 사용량 기록이 없습니다. 조회 실패·형식 미지원·자료 누락을0으로 해석하지 않습니다.</p>
   <article v-for="project in linkedUsage" :key="project.codeburnProjectId" class="resource-card"><h4>{{project.label}} · 선택 프로젝트와 연결된 기록</h4><p>{{project.match.state==='matched'?'저장소 경로 연결 확인':'일부 세션 경로만 연결 · 전체 귀속 미확인'}} · 추정 {{project.totalCost}} USD (이 CodeBurn 기록 묶음 전체, 실제 청구액 아님)</p><p>브랜치 자료 없는 세션 {{project.coverageEvidence.noBranchDataSessions}}개 · 해당 비용 {{project.coverageEvidence.noBranchDataCost}} USD · 전체자료 coverage 미확인</p><details><summary>브랜치·세션 근거</summary><section v-for="(branch,bi) in project.branches.slice(0,30)" :key="bi"><h5>{{branch.branch??'브랜치 미확인'}} · {{branch.cost}} USD · 호출 {{branch.calls}}</h5><ul><li v-for="session in branch.sessionRows.slice(0,30)" :key="session.sessionId">{{session.provider}} · {{session.sessionId}} · {{session.match.workstreamIds.includes(workstream.id)?'선택 프로젝트 경로와 일치':'이 프로젝트 귀속 미확인'}} · 입력 {{session.tokens.inputTokens}} / 출력 {{session.tokens.outputTokens}} · {{session.cost}} USD · DAG 태스크 연결 미확인</li></ul><p v-if="branch.sessionRows.length>30">세션 {{branch.sessionRows.length-30}}개 표시 생략</p></section><p v-if="project.branches.length>30">브랜치 {{project.branches.length-30}}개 표시 생략</p></details></article>
   <h4>같은 기간의 기록 묶음 비교</h4><p>프로젝트/계정 합계가 아닌 CodeBurn 원본 기록별 추정 비용입니다. 오래되거나 미확인인 값은 막대를 그리지 않습니다.</p><div v-for="project in repositoryUsage?.projects.slice(0,50)??[]" :key="project.codeburnProjectId" class="repository-cost-row"><span>{{project.label}} · {{project.totalCost}} USD · {{project.match.tier==='registered-project'?'등록 프로젝트':project.match.tier==='repository-unregistered'?'저장소 확인·프로젝트 미등록':'저장소 연결 미확인'}}</span><svg v-if="project.chartCost!==null&&maxRepositoryCost>0" viewBox="0 0 300 12" role="img" :aria-label="project.label+' 기록 비용 '+project.totalCost+' USD'"><rect x="0" y="0" :width="300*project.chartCost/maxRepositoryCost" height="12" rx="3" fill="currentColor"/></svg></div><p v-if="(repositoryUsage?.projects.length??0)>50">비교 항목 {{repositoryUsage!.projects.length-50}}개 표시 생략</p>
   <h4>프로젝트 미등록·미확인 기록</h4><div class="resource-grid"><article v-for="project in otherRepositoryUsage.slice(0,50)" :key="project.codeburnProjectId" class="resource-card"><strong>{{project.label}}</strong><p>{{project.match.tier==='repository-unregistered'?'저장소 확인 · 프로젝트 미등록':'저장소 연결 미확인'}}</p><p>원본 기록 ID {{project.codeburnProjectId}}</p><p>{{project.totalCost}} USD · DAG task 연결 미확인 · 현재 메모리 별도 미확인</p></article></div><p v-if="otherRepositoryUsage.length>50">추가 기록 {{otherRepositoryUsage.length-50}}개 표시 생략</p>
  </section>
  <h3>제공자 전체 역사 소비량</h3><p>CodeBurn의 추정 집계입니다. 이 프로젝트 비용이나 실제 청구액이 아닙니다. 오늘/월의 정확한 경계·시간대는 미확인입니다.</p>
  <table class="resource-table"><thead><tr><th>제공자·기간</th><th>관측 비용</th><th>호출</th><th>현재성·출처</th></tr></thead><tbody><tr v-for="(period,i) in resources.usage.providerPeriods" :key="i"><td>{{period.provider}} · {{period.period}}</td><td>{{period.cost??'미확인'}} {{period.currency}}</td><td>{{period.calls??'미확인'}}</td><td>{{period.freshness}} · {{time(period.observedAt)}} · {{period.source}}</td></tr></tbody></table><p v-if="!resources.usage.providerPeriods.length">역사 소비량 자료 미관측</p>
  <ul><li v-for="observation in resources.usage.providerObservations" :key="observation.provider">{{observation.provider}} · {{observation.state}} · {{observation.error??'오류 보고 없음'}} · 마지막 시도 {{time(observation.lastAttemptAt)}} · 마지막 성공 {{time(observation.lastSuccess)}}</li></ul><h3>프로젝트 미등록 작업 · 저장소별</h3><p>DAG 태스크 연결 여부는 프로젝트 등록과 별개입니다. 태스크 ID가 없는 응답만으로 미등재라고 단정하지 않습니다.</p><div class="resource-grid"><article v-for="row in unregistered" :key="row.workstreamId" class="resource-card"><h4>{{row.title}}</h4><p>{{row.tier==='repository-unregistered'?'저장소 확인 · 프로젝트 미등록':'저장소 미확인'}}</p><pre class="evidence-text">{{JSON.stringify({repository:row.repository,taskLinkage:row.taskLinkage},null,2)}}</pre><p>역사 소비량·현재 메모리 미확인</p></article></div><p v-if="!unregistered.length">현재 관측 범위에서 미등록 작업이 없습니다. 관측 범위 밖의 작업은 확인되지 않았습니다.</p>
  <section class="resource-card" data-testid="dispatch-advisory"><h3>추가 파견 판단 참고</h3><strong>{{advisory.state==='hold-advised'?'보류 검토 권고':advisory.state==='insufficient-observation'?'판단 근거 부족':'관측한 보류 사유 없음'}}</strong><p>실행 허가나 강제 차단이 아닙니다. 실제 실행은 Orca에서 판단합니다. unknown·오래된 자료를 실행 가능으로 바꾸지 않습니다.</p><ul><li v-for="(reason,i) in advisory.reasons.slice(0,20)" :key="i">{{reason.detail}} · {{reason.source}} · {{time(reason.observedAt)}}</li></ul><p v-if="advisory.reasons.length>20">추가 사유 {{advisory.reasons.length-20}}개 표시 생략</p><label><input v-model="acknowledged" type="checkbox"> 권고를 읽었습니다 (실행 제어 없음)</label><p class="muted">정책 {{advisory.policy.id}} v{{advisory.policy.version}} · 기존 관측의 화면 계산만 수행</p></section>
  <details><summary>수집 capability와 남은 검증</summary><pre class="evidence-text">{{JSON.stringify(resources.capabilities,null,2)}}</pre><p>공식 계정별 수집·실제 Mac 메모리 연계·저장소별 branch 수집의 실제 설치 버전·자료 포함 범위는 재확인이 필요합니다. private cache·인증 정보는 조회하지 않습니다.</p></details>
 </section>
</template>
