import {_electron as electron} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {buildIdentity,assertTrackedProcessesExit} from './evidence.mjs';
import path from 'node:path';
const evidence=path.resolve('reviews/evidence');
await mkdir(evidence,{recursive:true});
const codeIdentity=await buildIdentity();
let app;
const checks=[];
const screenshot=async(page,name)=>{await page.screenshot({path:path.join(evidence,name),fullPage:true});};
try{
  app=await electron.launch({chromiumSandbox:true,args:[path.resolve('.')],timeout:30000});
  const pid=app.process().pid;
  const page=await app.firstWindow();
  const consoleErrors=[];
  page.on('pageerror',error=>consoleErrors.push(String(error)));
  await page.getByRole('heading',{name:'아직 연결된 데이터가 없어요'}).waitFor();
  const environment=await page.evaluate(()=>window.noteApp.getEnvironment());
  assert.deepEqual(environment.capabilities,{realOrca:false,noteWrites:false,remoteSummary:false});
  await screenshot(page,'T-007-initial.png');
  checks.push('Initial state: no real sources, no automatic fixture or summary execution');
  const security=await app.evaluate(({BrowserWindow})=>{
    const window=BrowserWindow.getAllWindows()[0];
    const {sandbox,contextIsolation,nodeIntegration,webSecurity,webviewTag}=window.webContents.getLastWebPreferences();
    return {sandbox,contextIsolation,nodeIntegration,webSecurity,webviewTag,argv:process.argv,versions:process.versions};
  });
  assert.equal(security.sandbox,true);assert.equal(security.contextIsolation,true);assert.equal(security.nodeIntegration,false);assert.equal(security.webSecurity,true);assert.equal(security.webviewTag,false);
  assert(!security.argv.some(arg=>arg.includes('no-sandbox')));
  const exposed=await page.evaluate(()=>({require:typeof window.require,process:typeof window.process,keys:Object.keys(window.noteApp).sort()}));
  assert.deepEqual(exposed,{require:'undefined',process:'undefined',keys:['approveSummary','cancelNoteLink','cancelSummary','confirmNoteLink','connectLive','disconnectLive','getEnvironment','getLiveState','getPhase1Options','loadDemo','onLiveState','onSummary','prepareSummary','previewNoteLink','readSummary','refreshLive','rejectSummary','runSummary']});
  for(const invalid of [null,{}, {scenario:'real'}, {scenario:'normal',path:'/etc/passwd'},{scenario:'normal',command:'echo injected'}]){
    await assert.rejects(page.evaluate(request=>window.noteApp.loadDemo(request),invalid),/Invalid demo/);
  }
  checks.push('Runtime security: sandbox/context isolation on; Node absent; narrow API; malformed and path/command-shaped requests rejected');
  await page.evaluate(()=>window.open('https://example.com'));
  assert.equal(app.windows().length,1);
  await assert.rejects(page.evaluate(()=>fetch('https://example.com').then(r=>r.text())));
  const isolatedFrame=await page.evaluate(()=>{const frame=document.createElement('iframe');frame.hidden=true;document.body.append(frame);const result=typeof frame.contentWindow.noteApp;frame.remove();return result;});
  assert.equal(isolatedFrame,'undefined');
  const foreignRejected=await app.evaluate(async({BrowserWindow,app})=>{
    const foreign=new BrowserWindow({show:false,webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,preload:app.getAppPath()+'/dist/preload/index.cjs'}});
    try{await foreign.loadFile(app.getAppPath()+'/dist/renderer/index.html');return await foreign.webContents.executeJavaScript("window.noteApp.getEnvironment().then(()=>false,error=>error.message.includes('Untrusted IPC sender'))");}finally{foreign.close();}
  });
  assert.equal(foreignRejected,true);
  checks.push('Remote fetch/new external windows blocked; real child frame has no IPC bridge; foreign Electron window IPC rejected');
  await page.getByRole('button',{name:'샘플로 살펴보기',exact:true}).focus();
  await page.keyboard.press('Enter');
  await page.getByText('가상 프로젝트 샘플',{exact:true}).waitFor();
  const initialCount=await page.locator('.workstream-card').count();
  assert(initialCount>0);
  await screenshot(page,'T-007-overview.png');
  await page.getByRole('button',{name:/전체 비보관/}).click();
  const allCount=await page.locator('.workstream-card').count();
  assert(allCount>initialCount);
  await page.getByLabel('작업 검색').fill('there-is-no-such-project-999');
  await page.getByRole('heading',{name:'검색 결과가 없어요'}).waitFor();
  await page.getByRole('button',{name:'검색어 지우기'}).click();
  assert.equal(await page.locator('.workstream-card').count(),allCount);
  await page.getByLabel('작업 검색').fill('Atlas');
  const firstTitle=await page.locator('.workstream-card h2 a').first().textContent();
  await page.locator('.workstream-card h2 a').first().click();
  await page.getByRole('heading',{name:'작업의 맥락',exact:true}).waitFor();
  await page.goBack();
  await page.getByLabel('작업 검색').waitFor();
  assert.equal(await page.getByLabel('작업 검색').inputValue(),'Atlas');
  await page.goForward();
  await page.getByRole('heading',{name:'작업의 맥락',exact:true}).waitFor();
  await page.locator('.evidence summary').focus();
  await page.keyboard.press('Space');
  await page.locator('.evidence-body').waitFor();
  await screenshot(page,'T-007-detail.png');
  await page.getByRole('link',{name:'← 프로젝트 현황으로'}).click();
  assert.equal(await page.getByLabel('작업 검색').inputValue(),'Atlas');
  await page.getByLabel('작업 검색').fill('');
  assert.equal(await page.locator('.workstream-card').count(),allCount);
  checks.push(`User navigation: ${initialCount} connected → ${allCount} nonarchived workstreams; no-result search/clear; detail/evidence/back (${firstTitle?.trim()})`);
  await page.locator('.demo-controls summary').click();
  const originalObservation=await page.locator('.observation').textContent();
  await page.getByLabel('데이터 상태').selectOption('failure');
  await page.getByRole('button',{name:'선택한 예시 적용'}).click();
  await page.getByText('갱신 실패 · 이전 내용 유지',{exact:true}).waitFor();
  assert.equal(await page.locator('.workstream-card').count(),allCount);
  assert.equal(await page.locator('.observation').textContent(),originalObservation);
  await screenshot(page,'T-007-stale.png');
  await page.locator('.workstream-card h2 a').first().click();
  await page.getByRole('heading',{name:'작업의 맥락',exact:true}).waitFor();
  await screenshot(page,'T-007-stale-detail.png');
  await page.getByText('갱신 실패 · 이전 내용 유지',{exact:true}).waitFor({timeout:3000});
  await page.getByText('실패한 시도',{exact:false}).waitFor();
  assert((await page.getByText('이전 관측',{exact:true}).count())>0);
  await page.getByRole('link',{name:'← 프로젝트 현황으로'}).click();
  await page.locator('.demo-controls summary').click();
  await page.getByLabel('데이터 상태').selectOption('normal');
  await page.getByRole('button',{name:'선택한 예시 적용'}).click();
  assert.equal(await page.getByText('갱신 실패 · 이전 내용 유지',{exact:true}).count(),0);
  for(let i=0;i<3;i++) await page.getByRole('button',{name:'새로고침',exact:true}).click();
  assert.equal(await page.locator('.workstream-card').count(),allCount);
  await page.getByLabel('데이터 상태').selectOption('empty');
  await page.getByRole('button',{name:'선택한 예시 적용'}).click();
  await page.getByRole('heading',{name:'확인된 비보관 작업이 없어요'}).waitFor();
  await page.getByLabel('데이터 상태').selectOption('failure');
  await page.getByRole('button',{name:'선택한 예시 적용'}).click();
  await page.getByText('갱신 실패 · 이전 내용 유지',{exact:true}).waitFor();
  assert.equal(await page.locator('.workstream-card').count(),0);
  checks.push('Synthetic failure keeps last-good workstreams and timestamp, including empty → failure;  normal retry recovers; repeated refreshes stable; explicit empty success separate');
  await page.getByRole('link',{name:'연결 및 설정',exact:true}).click();
  await page.getByText('실제 AI 호출은 안전한 실행 경계가 검증될 때까지 차단됩니다.',{exact:false}).waitFor();
  await screenshot(page,'T-007-settings.png');
  await page.getByRole('button',{name:'샘플 모드 종료'}).click();
  await page.getByRole('heading',{name:'아직 연결된 데이터가 없어요'}).waitFor();
  await page.evaluate(()=>location.hash='/workstream/missing');
  await page.getByRole('heading',{name:'이 작업을 찾을 수 없어요'}).waitFor();
  await page.getByRole('link',{name:'현황으로 돌아가기',exact:true}).click();
  await page.getByRole('button',{name:'샘플로 살펴보기',exact:true}).click();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(800,760));
  await screenshot(page,'T-007-narrow.png');
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
  assert.equal(overflow,false);
  const hostileText='<img src=x onerror="window.__hostileExecuted=true">';
  const hostileSnapshot=await page.evaluate(()=>window.noteApp.loadDemo({scenario:'normal'}));
  const unknown=hostileSnapshot.workstreams[2];unknown.worktrees[0].terminalConnected=null;unknown.worktrees[0].terminalCount=null;unknown.goal.text=hostileText;
  await app.evaluate(({ipcMain},snapshot)=>{ipcMain.removeHandler('note-app:demo');ipcMain.handle('note-app:demo',()=>snapshot);},hostileSnapshot);
  await page.getByRole('button',{name:'새로고침',exact:true}).click();
  await page.getByRole('button',{name:/전체 비보관/}).click();
  await page.getByText('터미널 연결 미확인',{exact:true}).waitFor();
  await page.getByText(hostileText,{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.__hostileExecuted),undefined);
  assert.equal(await page.locator('img[src="x"]').count(),0);
  await screenshot(page,'T-007-unknown-untrusted.png');
  checks.push('Test-injected unknown connectivity stays unknown; hostile markup renders as plain text without creating an image or running script');
  const beforeRejectedRefresh=await page.locator('.observation').textContent();
  const beforeRejectedCount=await page.locator('.workstream-card').count();
  await app.evaluate(({ipcMain})=>ipcMain.removeHandler('note-app:demo'));
  await page.getByRole('button',{name:'새로고침',exact:true}).click();
  await page.getByText('앱 연결 오류로 갱신하지 못했습니다.',{exact:false}).waitFor();
  assert.equal(await page.locator('.observation').textContent(),beforeRejectedRefresh);
  assert.equal(await page.locator('.workstream-card').count(),beforeRejectedCount);
  await screenshot(page,'T-007-ipc-failure.png');
  checks.push('Actual missing IPC handler rejects refresh: visible error/stale state retains prior cards and timestamp');
  await page.reload();
  await page.getByRole('heading',{name:'아직 연결된 데이터가 없어요'}).waitFor();
  assert.deepEqual(consoleErrors,[]);
  checks.push('Exit demo clears state; missing detail safe; re-entry; narrow-window layout without horizontal overflow; reload safe; no renderer exceptions');
  const metrics=await app.evaluate(({app})=>app.getAppMetrics().map(({pid,type,cpu,memory})=>({pid,type,cpu,memory})));
  await app.close();app=undefined;
  await assertTrackedProcessesExit([...new Set([pid,...metrics.map(metric=>metric.pid)])]);
  checks.push('Window closes and all main/renderer/GPU/utility processes tracked by Electron metrics exit');
  const result={status:'passed',observedAt:new Date().toISOString(),codeIdentity,security,environment,checks,metrics,scope:'Linux development build with synthetic/manual fixture only; not real Orca, notes, macOS native dialogs or packaged .app',visualReview:'Pending separate image opening'};
  await writeFile(path.join(evidence,'T-007-result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{if(app)await app.close();}
