import test from 'node:test';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';
import {mkdtemp,realpath,mkdir,writeFile,rm,symlink,chmod,rename} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {runNativeFixtureTransactionForTests as run} from '../../scripts/updater/install-transaction.mjs';
import {pathsFor} from '../../scripts/updater/protocol.mjs';
async function fixture(t){const home=await realpath(await mkdtemp(path.join(os.tmpdir(),'note-app-native-fixture-')));t.after(()=>rm(home,{recursive:true,force:true}));const p=pathsFor(home,'a'.repeat(32));await mkdir(p.directory,{recursive:true,mode:0o700});await mkdir(path.dirname(p.canonical),{mode:0o700});const marker={kind:'note-app-native-fixture',ownerPid:process.pid,home,token:'b'.repeat(64)};const json=(f,x)=>writeFile(f,JSON.stringify(x),{mode:0o600});await json(path.join(home,'native-fixture-owner.json'),marker);const plan={schemaVersion:1,transactionId:'a'.repeat(32),createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+600000).toISOString(),currentPid:88881,current:{sourceSha:'1'.repeat(40),buildNumber:'1'},target:{sourceSha:'2'.repeat(40),sourceTree:'3'.repeat(40),buildNumber:'2',version:'0.1.0',architecture:'arm64',appSha256:'4'.repeat(64)},nonce:'5'.repeat(64)};await json(p.plan,plan);for(const bundle of [p.canonical,p.stage]){await mkdir(path.join(bundle,'Contents/Resources/app'),{recursive:true,mode:0o700});await json(path.join(bundle,'Contents/Resources/app/package.json'),{nativeFixture:marker});}return {home,p,marker,json,options:{testOnly:true,home,planPath:p.plan}};}
test('native seam rejects real home and injected lifecycle/platform regardless of OS',async()=>{await assert.rejects(run({testOnly:true,home:os.userInfo().homedir,planPath:'/tmp/plan.json'}),/Unsafe native/);await assert.rejects(run({testOnly:true,home:'/tmp/x',planPath:'/tmp/plan.json',lifecycle:{}}),/fields/);await assert.rejects(run({testOnly:true,home:'/tmp/x',planPath:'/tmp/plan.json',platform:'darwin'}),/fields/);});
test('native seam rejects absent testOnly and out-of-range deadlines',async t=>{const f=await fixture(t);for(const extra of [{testOnly:false},{bootTimeoutMs:0},{bootTimeoutMs:45001},{recovery:'yes'}])await assert.rejects(run({...f.options,...extra}),/Unsafe native/);});
test('native seam rejects fixture owned by another harness',async t=>{const f=await fixture(t);await f.json(path.join(f.home,'native-fixture-owner.json'),{...f.marker,ownerPid:process.pid+1});await assert.rejects(run(f.options),/ownership/);});
test('native seam rejects a bundle not carrying this exact fixture marker',async t=>{const f=await fixture(t);await f.json(path.join(f.p.stage,'Contents/Resources/app/package.json'),{nativeFixture:{...f.marker,token:'c'.repeat(64)}});await assert.rejects(run(f.options),/owned native fixture/);});
test('native recovery cannot use an unowned backup when canonical is absent',async t=>{const f=await fixture(t);await rename(f.p.canonical,f.p.backup);await f.json(path.join(f.p.backup,'Contents/Resources/app/package.json'),{nativeFixture:{...f.marker,token:'c'.repeat(64)}});await assert.rejects(run({...f.options,recovery:true}),/owned native fixture/);});
test('native seam rejects nonprivate root and symlink marker before native operations',async t=>{const f=await fixture(t);await chmod(f.home,0o755);await assert.rejects(run(f.options),/permissions/);await chmod(f.home,0o700);const marker=path.join(f.home,'native-fixture-owner.json');await rm(marker);await f.json(path.join(f.home,'real-marker.json'),f.marker);await symlink('real-marker.json',marker);await assert.rejects(run(f.options),/Symlink/);});
test('production CLI cannot select fixture home or native test mode',()=>{for(const args of [['--fixture-home','/tmp/x'],['--test-only'],['--platform','darwin']])assert.throws(()=>execFileSync(process.execPath,['scripts/update-installer.mjs','--plan','/tmp/plan.json',...args],{stdio:'pipe'}));});
