import {it,expect} from 'vitest';
import {mkdtemp,writeFile,chmod,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createClaudePublicAdapter,assertSubscriptionAuthentication} from '../../src/summary/reading/claude-public-adapter';
import type {PublicReadingPack,ModelBinding} from '../../src/summary/reading/model-harness';
const binding:ModelBinding={runId:'fixture-run',project:'zeno0505/note-app',inputHash:'a'.repeat(64),version:'public-reading-v1',attempt:1};
const pack={project:'zeno0505/note-app',sourceSha:'a'.repeat(40),sources:[],facts:[]} as PublicReadingPack;
async function fixture(authMethod='claude.ai',hang=false){
  const root=await mkdtemp(path.join(os.tmpdir(),'claude-public-fixture-')),executable=path.join(root,'synthetic-claude'),log=path.join(root,'calls.jsonl');
  await writeFile(executable,`#!${process.execPath}\nconst fs=require('node:fs');const args=process.argv.slice(2);fs.appendFileSync(${JSON.stringify(log)},JSON.stringify({args,apiKey:process.env.ANTHROPIC_API_KEY??null,home:process.env.HOME})+'\\n');if(args.includes('auth')){console.log(JSON.stringify({loggedIn:true,authMethod:${JSON.stringify(authMethod)},apiProvider:'firstParty',subscriptionType:'team',email:'DO_NOT_RECORD@example.invalid'}));}else{let data='';process.stdin.on('data',x=>data+=x);process.stdin.on('end',()=>{${hang?"setInterval(()=>{},1000);":"console.log(JSON.stringify({type:'result',subtype:'success',is_error:false,structured_output:{ok:true},usage:{input_tokens:7},num_turns:2}));"}});}\n`);await chmod(executable,0o700);
  return {root,executable,log,env:{HOME:root,PATH:process.env.PATH,ANTHROPIC_API_KEY:'SYNTHETIC_API_KEY_FORBIDDEN'},clean:()=>rm(root,{recursive:true,force:true})};
}
it('accepts only an existing claude.ai firstParty subscription without recording identity',async()=>{const f=await fixture();try{expect(assertSubscriptionAuthentication(f.executable,f.root,f.env)).toEqual({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty',subscriptionType:'team'});expect(JSON.parse((await readFile(f.log,'utf8')).trim()).apiKey).toBeNull();}finally{await f.clean();}});
it('blocks API authentication before spawning any model request',async()=>{const f=await fixture('api_key');try{const adapter=createClaudePublicAdapter(f.executable,f.root,f.env);expect(()=>adapter.generate({binding,pack,repairErrors:[]},new AbortController().signal)).toThrow('Existing subscription login required');const calls=(await readFile(f.log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));expect(calls.length).toBe(1);expect(calls[0].args).toContain('auth');}finally{await f.clean();}});
it('requires a completed result and uses fixed no-tools/no-MCP args and sanitized env',async()=>{const f=await fixture();try{const result=await createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},new AbortController().signal);expect(result.answer).toEqual({ok:true});expect(result.usage).toEqual({usage:{input_tokens:7},num_turns:2});const rows=(await readFile(f.log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));expect(rows.length).toBe(2);expect(rows[1].args).toContain('--tools');expect(rows[1].args).toContain('');expect(rows[1].args).toContain('{"mcpServers":{}}');expect(rows[1].apiKey).toBeNull();expect(rows[1].args).not.toContain('--bare');}finally{await f.clean();}});
it('cancels only its owned fixture process and settles before returning',async()=>{const f=await fixture('claude.ai',true);try{const controller=new AbortController(),promise=createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},controller.signal);setTimeout(()=>controller.abort(),50);await expect(promise).rejects.toThrow('Cancelled owned model process');}finally{await f.clean();}});
