import {it,expect} from 'vitest';
import {mkdtemp,writeFile,chmod,readFile,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createClaudePublicAdapter,assertSubscriptionAuthentication} from '../../src/summary/reading/claude-public-adapter';
import type {PublicReadingPack,ModelBinding} from '../../src/summary/reading/model-harness';
const binding:ModelBinding={runId:'fixture-run',project:'zeno0505/note-app',inputHash:'a'.repeat(64),version:'public-reading-v1',attempt:1};
const pack={project:'zeno0505/note-app',sourceSha:'a'.repeat(40),sources:[],facts:[]} as PublicReadingPack;
async function fixture(authMethod='claude.ai',hang=false,authDelayMs=0){
  const root=await mkdtemp(path.join(os.tmpdir(),'claude-public-fixture-')),executable=path.join(root,'synthetic-claude'),log=path.join(root,'calls.jsonl');
  await writeFile(executable,`#!${process.execPath}\nconst fs=require('node:fs');const args=process.argv.slice(2);fs.appendFileSync(${JSON.stringify(log)},JSON.stringify({args,apiKey:process.env.ANTHROPIC_API_KEY??null,home:process.env.HOME})+'\\n');if(args.includes('auth')){setTimeout(()=>console.log(JSON.stringify({loggedIn:true,authMethod:${JSON.stringify(authMethod)},apiProvider:'firstParty',subscriptionType:'team',email:'DO_NOT_RECORD@example.invalid'})),${authDelayMs});}else{let data='';process.stdin.on('data',x=>data+=x);process.stdin.on('end',()=>{${hang?"setInterval(()=>{},1000);":"console.log(JSON.stringify({type:'result',subtype:'success',is_error:false,structured_output:{ok:true},usage:{input_tokens:7},num_turns:2}));"}});}\n`);await chmod(executable,0o700);
  return {root,executable,log,env:{HOME:root,PATH:process.env.PATH,ANTHROPIC_API_KEY:'SYNTHETIC_API_KEY_FORBIDDEN'},clean:()=>rm(root,{recursive:true,force:true})};
}
it('accepts only an existing claude.ai firstParty subscription without recording identity',async()=>{const f=await fixture();try{expect(assertSubscriptionAuthentication(f.executable,f.root,f.env)).toEqual({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty',subscriptionType:'team'});expect(JSON.parse((await readFile(f.log,'utf8')).trim()).apiKey).toBeNull();}finally{await f.clean();}});
it('blocks API authentication before spawning any model request',async()=>{const f=await fixture('api_key');try{const adapter=createClaudePublicAdapter(f.executable,f.root,f.env);await expect(adapter.generate({binding,pack,repairErrors:[]},new AbortController().signal)).rejects.toThrow('Existing subscription login required');const calls=(await readFile(f.log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));expect(calls.length).toBe(1);expect(calls[0].args).toContain('auth');}finally{await f.clean();}});
it('requires a completed result and uses fixed no-tools/no-MCP args and sanitized env',async()=>{const f=await fixture();try{const events:string[]=[];const result=await createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},new AbortController().signal,async event=>{events.push(event);});expect(events).toEqual(['authentication','launch-requested','started']);expect(result.answer).toEqual({ok:true});expect(result.usage).toEqual({usage:{input_tokens:7},num_turns:2});const rows=(await readFile(f.log,'utf8')).trim().split('\n').map(x=>JSON.parse(x));expect(rows.length).toBe(2);expect(rows[1].args).toContain('--tools');expect(rows[1].args).toContain('');expect(rows[1].args).toContain('{"mcpServers":{}}');expect(rows[1].apiKey).toBeNull();expect(rows[1].args).not.toContain('--bare');}finally{await f.clean();}});
it('cancels only its owned fixture process and settles before returning',async()=>{const f=await fixture('claude.ai',true);try{const controller=new AbortController(),promise=createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},controller.signal);const deadline=Date.now()+2000;while(Date.now()<deadline){const rows=await readFile(f.log,'utf8').catch(()=>'');if(rows.includes('\"-p\"'))break;await new Promise(r=>setTimeout(r,5));}controller.abort();await expect(promise).rejects.toThrow('Cancelled owned model process');}finally{await f.clean();}});

it('keeps authentication asynchronous and aborts before any paid spawn',async()=>{const f=await fixture('claude.ai',false,500);try{const controller=new AbortController();const pending=createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},controller.signal);let eventLoopContinued=false;await new Promise<void>(resolve=>setTimeout(()=>{eventLoopContinued=true;controller.abort();resolve();},30));expect(eventLoopContinued).toBe(true);await expect(pending).rejects.toThrow('Cancelled during auth status');const rows=(await readFile(f.log,'utf8').catch(()=>'')).trim().split('\n').filter(Boolean).map(x=>JSON.parse(x));expect(rows.some(r=>r.args.includes('-p'))).toBe(false);}finally{await f.clean();}});

it('classifies exit, malformed JSON and rejected/incomplete responses with only bounded process metadata',async()=>{
  const {ModelProcessFailure}=await import('../../src/summary/reading/model-process-failure');
  for(const [body,code] of [["process.stderr.write('PRIVATE_AUTH_AND_NOTE');process.exit(7)",'model_exited_unsuccessfully'],["console.log('PRIVATE_BAD_JSON')",'model_json_invalid'],["console.log(JSON.stringify({type:'result',is_error:true,result:'PRIVATE_REPLY'}))",'model_result_rejected'],["console.log(JSON.stringify({type:'result',subtype:'success'}))",'model_result_incomplete']] as const){
    const f=await fixture();try{await writeFile(f.executable,`#!${process.execPath}\nif(process.argv.includes('auth'))console.log(JSON.stringify({loggedIn:true,authMethod:'claude.ai',apiProvider:'firstParty',subscriptionType:'team'}));else{process.stdin.resume();process.stdin.on('end',()=>{${body}});}\n`);
      let failure:unknown;try{await createClaudePublicAdapter(f.executable,f.root,f.env).generate({binding,pack,repairErrors:[]},new AbortController().signal);}catch(e){failure=e;}
      expect(failure).toBeInstanceOf(ModelProcessFailure);const safe=failure as InstanceType<typeof ModelProcessFailure>;expect(safe.code).toBe(code);expect(safe.processInfo).toMatchObject({exitCode:code==='model_exited_unsuccessfully'?7:0,signal:'none',cleanup:'verified'});expect(safe.processInfo.durationMs).toBeGreaterThanOrEqual(0);expect(JSON.stringify(safe)).not.toMatch(/PRIVATE|AUTH_AND_NOTE|BAD_JSON|REPLY/);
    }finally{await f.clean();}
  }
});
