import {it,expect} from 'vitest';
import {mkdtemp,realpath,rm,readFile,symlink,mkdir,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';import path from 'node:path';
import {createModelDiagnostics,diagnosticProject,diagnosticCorrelation,ModelDiagnosticError,diagnosticCode} from '../../src/main/model-diagnostics';
async function fixture(){const root=await realpath(await mkdtemp(path.join(tmpdir(),'safe-model-diagnostics-')));return {root,directory:path.join(root,'diagnostics'),clean:()=>rm(root,{recursive:true,force:true})};}
const row=()=>({correlationId:diagnosticCorrelation(),projectId:diagnosticProject('opaque-project'),stage:'source-check' as const,code:'request_started' as const,modelCall:'not-started' as const,attempt:null});
it('persists only exact metadata fields, isolates projects and restores after restart without leaking private exceptions',async()=>{const f=await fixture();try{const store=createModelDiagnostics(f.directory,'a'.repeat(40));const value=row();await store.append(value);expect((await createModelDiagnostics(f.directory,'a'.repeat(40)).view(value.projectId)).records).toHaveLength(1);expect((await store.view(diagnosticProject('other'))).records).toEqual([]);await expect(store.append({...value,code:'secret person@example.invalid' as never})).rejects.toThrow();await expect(store.append({...value,prompt:'PRIVATE'} as never)).rejects.toThrow();expect(diagnosticCode(Error('private secret person@example.invalid'),'source-check')).toBe('source_validation_failed');expect(diagnosticCode(new ModelDiagnosticError('dag_cleanup_unverified'),'source-check')).toBe('dag_cleanup_unverified');const text=await readFile(path.join(f.directory,'summary-cache-v1.json'),'utf8');expect(text).not.toMatch(/PRIVATE|person@|opaque-project/);expect((await stat(f.directory)).mode&0o777).toBe(0o700);expect((await stat(path.join(f.directory,'summary-cache-v1.json'))).mode&0o777).toBe(0o600);}finally{await f.clean();}});
it('serializes concurrent writes, rotates at 200 and prunes records older than 30 days on read or write',async()=>{const f=await fixture();try{let now='2026-10-01T00:00:00.000Z';const store=createModelDiagnostics(f.directory,null,()=>now);await Promise.all(Array.from({length:205},()=>store.append(row())));let data=JSON.parse(await readFile(path.join(f.directory,'summary-cache-v1.json'),'utf8'));expect(data.payload.records).toHaveLength(200);now='2026-11-02T00:00:00.000Z';expect((await store.view(row().projectId)).records).toEqual([]);expect(JSON.parse(await readFile(path.join(f.directory,'summary-cache-v1.json'),'utf8')).payload.records).toEqual([]);await store.append(row());data=JSON.parse(await readFile(path.join(f.directory,'summary-cache-v1.json'),'utf8'));expect(data.payload.records).toHaveLength(1);}finally{await f.clean();}},20000);
it('rejects symlink destinations and retains malformed data rather than overwriting it',async()=>{const f=await fixture();try{const outside=path.join(f.root,'outside');await mkdir(outside,{mode:0o700});await symlink(outside,f.directory);const unsafe=createModelDiagnostics(f.directory,null);await expect(unsafe.append(row())).rejects.toThrow('diagnostics_unavailable');expect((await unsafe.view(row().projectId)).available).toBe(false);await rm(f.directory);const store=createModelDiagnostics(f.directory,null);await store.append(row());const file=path.join(f.directory,'summary-cache-v1.json');const {writeFile}=await import('node:fs/promises');await writeFile(file,'DO_NOT_OVERWRITE');await expect(store.append(row())).rejects.toThrow();expect(await readFile(file,'utf8')).toBe('DO_NOT_OVERWRITE');}finally{await f.clean();}});

it('accepts safe process metadata alongside older records and rejects raw diagnostic properties',async()=>{const f=await fixture();try{const store=createModelDiagnostics(f.directory,null);await store.append(row());const value={...row(),stage:'model-call' as const,code:'model_json_invalid' as const,modelCall:'started' as const,process:{exitCode:0,signal:'none' as const,durationMs:3618,outputBytes:25,stderrBytes:0,cleanup:'verified' as const}};await store.append(value);expect((await store.view(value.projectId)).records[0].process).toEqual(value.process);await expect(store.append({...value,process:{...value.process,stderr:'PRIVATE'}} as never)).rejects.toThrow();await expect(store.append({...value,process:{...value.process,signal:'PRIVATE'}} as never)).rejects.toThrow();expect(await readFile(path.join(f.directory,'summary-cache-v1.json'),'utf8')).not.toContain('PRIVATE');}finally{await f.clean();}});
