import {it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import {mkdtemp,readFile,readdir,rm,realpath,symlink,stat} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {createModelReadingStorage,MODEL_LEDGER_LIMIT} from '../../src/summary/reading/model-reading-storage';
import {createPublicReadingHarness,publicInputHash,MODEL_HARNESS_VERSION,SECTION_IDS,type PublicReadingPack,type ModelBinding,type HarnessRecord,type ModelAnswer} from '../../src/summary/reading/model-harness';
const pack=(text='첫번째'):PublicReadingPack=>({project:'zeno0505/note-app',sourceSha:'a'.repeat(40),sources:[{id:'S1',path:'src/public.ts',lineStart:1,lineEnd:1,sha256:createHash('sha256').update('PUBLIC_RAW_SOURCE_CANARY').digest('hex'),excerpt:'PUBLIC_RAW_SOURCE_CANARY'}],facts:SECTION_IDS.map((section,i)=>({id:'F'+i,section,state:'known',text:'공개 근거 '+text,sourceIds:['S1'],anchors:[text]}))});
function answer(binding:ModelBinding,p:PublicReadingPack):ModelAnswer{return {...binding,sections:SECTION_IDS.map(id=>({id,text:p.facts.find(f=>f.section===id)!.text,facts:p.facts.filter(f=>f.section===id).map(f=>({id:f.id,state:f.state})),sourceIds:['S1']}))};}
async function fixture(){const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'latest-reading-'))),directory=path.join(root,'model-reading');return {root,directory,storage:createModelReadingStorage(directory),clean:()=>rm(root,{recursive:true,force:true})};}
async function success(f:Awaited<ReturnType<typeof fixture>>,p:PublicReadingPack){return createPublicReadingHarness({generate:async r=>({answer:answer(r.binding,p),provider:'fixture',runtimeMs:12,usage:{usage:{input_tokens:7,output_tokens:9},unneededBody:'UNNEEDED_BODY_CANARY'}})},f.storage.ledger(p)).summarize(p);}
it('stores exactly one latest body and a distinct compact no-replay ledger without source text',async()=>{const f=await fixture();try{await success(f,pack());await success(f,pack('두번째'));const dirs=await readdir(f.directory),latestDir=dirs.find(d=>d.startsWith('latest-'))!;expect(dirs.filter(d=>d.startsWith('latest-')).length).toBe(1);const latest=await readFile(path.join(f.directory,latestDir,'summary-cache-v1.json'),'utf8'),ledger=await readFile(path.join(f.directory,'ledger','summary-cache-v1.json'),'utf8');expect(latest).toContain('두번째');expect(latest).not.toContain('첫번째');expect(latest).not.toContain('PUBLIC_RAW_SOURCE_CANARY');expect(ledger).not.toContain('두번째');expect(ledger).not.toContain('첫번째');expect(ledger).not.toContain('UNNEEDED_BODY_CANARY');expect(JSON.parse(ledger).payload.runs.length).toBe(2);expect((await stat(path.join(f.directory,latestDir,'summary-cache-v1.json'))).mode&0o077).toBe(0);}finally{await f.clean();}});
it('restores latest across restart and spends no additional calls for current or older successful input',async()=>{const f=await fixture();try{const first=pack(),second=pack('최신');await success(f,first);const latest=await success(f,second);let calls=0;const reopened=createModelReadingStorage(f.directory);const adapter={generate:async()=>{calls++;throw Error('must not call');}};expect((await createPublicReadingHarness(adapter,reopened.ledger(second)).summarize(second)).answer).toEqual(latest.answer);expect((await createPublicReadingHarness(adapter,reopened.ledger(first)).summarize(first)).status).toBe('fallback');expect(calls).toBe(0);expect((await reopened.readLatest(second.project)).state).toBe('ready');}finally{await f.clean();}});
it('failed changed input leaves prior body unchanged and explicitly stale',async()=>{const f=await fixture();try{await success(f,pack());const before=await f.storage.readLatest(pack().project);const changed=pack('실패');const failed=await createPublicReadingHarness({generate:async()=>{throw Error('fixture failure');}},f.storage.ledger(changed)).summarize(changed);expect(failed.status).toBe('fallback');const after=await f.storage.readLatest(changed.project);expect(after.state).toBe('stale');expect('latest' in after&&'latest' in before&&after.latest).toEqual('latest' in before&&before.latest);}finally{await f.clean();}});
it('cancelled and late runs cannot overwrite a successful body',async()=>{const f=await fixture();try{await success(f,pack());const changed=pack('취소'),ledger=f.storage.ledger(changed),inputHash=publicInputHash(changed),runId='cancelled-run';const pending:HarnessRecord={inputHash,runId,attempts:1,status:'running',errors:[],receipts:[]};await ledger.put(pending);await ledger.put({...pending,status:'cancelled'});const b:ModelBinding={runId,project:changed.project,inputHash,version:MODEL_HARNESS_VERSION,attempt:1};await expect(ledger.put({...pending,status:'model',answer:answer(b,changed)})).rejects.toThrow('Retired');expect((await f.storage.readLatest(changed.project)).state).toBe('stale');}finally{await f.clean();}});
it('an aborted atomic replacement preserves previous bytes',async()=>{const f=await fixture();try{await success(f,pack());const changed=pack('중단'),ledger=f.storage.ledger(changed),inputHash=publicInputHash(changed),runId='aborted-run',pending:HarnessRecord={inputHash,runId,attempts:1,status:'running',errors:[],receipts:[]};await ledger.put(pending);const before=await f.storage.readLatest(changed.project),controller=new AbortController();controller.abort();await expect(ledger.put({...pending,status:'model',answer:answer({runId,project:changed.project,inputHash,version:MODEL_HARNESS_VERSION,attempt:1},changed)},controller.signal)).rejects.toThrow();const after=await f.storage.readLatest(changed.project);expect('latest' in after&&after.latest).toEqual('latest' in before&&before.latest);}finally{await f.clean();}});
it('migrates an approved public result without calls, retains its observed time and semantic caveat',async()=>{const f=await fixture();try{const p=pack(),inputHash=publicInputHash(p),b:ModelBinding={runId:'legacy-run',project:p.project,inputHash,version:MODEL_HARNESS_VERSION,attempt:1},record:HarnessRecord={inputHash,attempts:1,status:'model',answer:answer(b,p),errors:[],receipts:[{provider:'fixture',runtimeMs:10,usage:{usage:{input_tokens:2}}}]};await f.storage.importSuccessfulPublicResult(p,record,'공개 입력 한정 검수','2026-10-01T00:00:00Z');await f.storage.importSuccessfulPublicResult(p,record,'공개 입력 한정 검수','2026-10-01T00:00:00Z');const view=await f.storage.readLatest(p.project);expect(view.state).toBe('ready');expect('latest' in view&&view.latest.generatedAt).toBe('2026-10-01T00:00:00Z');expect('latest' in view&&view.latest.validation.semantic).toBe('reviewed-with-scope-note');}finally{await f.clean();}});
it('caps metadata and refuses new calls without erasing past no-replay reservations',async()=>{const f=await fixture();try{for(let i=0;i<MODEL_LEDGER_LIMIT;i++){const p=pack('입력'+i);await f.storage.ledger(p).put({inputHash:publicInputHash(p),runId:'run-'+i,attempts:1,status:'running',errors:[],receipts:[]});}const extra=pack('상한초과');let calls=0;await expect(createPublicReadingHarness({generate:async()=>{calls++;throw Error('unexpected');}},f.storage.ledger(extra)).summarize(extra)).rejects.toThrow('ledger full');expect(calls).toBe(0);const x=JSON.parse(await readFile(path.join(f.directory,'ledger','summary-cache-v1.json'),'utf8'));expect(x.payload.runs.length).toBe(MODEL_LEDGER_LIMIT);expect(await f.storage.ledger(pack('입력0')).get(publicInputHash(pack('입력0')))).toBeDefined();}finally{await f.clean();}},15000);
it('missing cache reads empty without writing; unsafe linked storage fails closed',async()=>{const f=await fixture();try{expect((await f.storage.readLatest(pack().project)).state).toBe('empty');expect(await readdir(f.root)).toEqual([]);await symlink(f.root,f.directory);await expect(f.storage.ledger(pack()).lock()).rejects.toThrow('Unsafe');expect((await f.storage.readLatest(pack().project)).state).toBe('unavailable');}finally{await f.clean();}});
