import {it,expect} from 'vitest';
import fs from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {execFileSync} from 'node:child_process';
import {createNoteReconnect} from '../../src/main/note-reconnect';
async function fixture(){
 const root=await fs.realpath(await fs.mkdtemp(path.join(tmpdir(),'note-reconnect-'))),tree=path.join(root,'tree'),vault=path.join(root,'vault'),note=path.join(vault,'chosen');
 await fs.mkdir(tree);await fs.mkdir(note,{recursive:true});await fs.writeFile(path.join(note,'dag.yaml'),'tasks: []');await fs.writeFile(path.join(note,'private-note'),'KEEP');execFileSync('/usr/bin/git',['init','-q',tree]);
 const options={resolve:(id:string)=>id==='opaque'?{worktreePath:tree}:null,allowed:async(p:string)=>p.startsWith(vault+path.sep)};
 const service=createNoteReconnect(options);return {root,tree,vault,note,options,service,link:path.join(tree,'docs/note'),clean:()=>fs.rm(root,{recursive:true,force:true})};
}
const apply=(service:ReturnType<typeof createNoteReconnect>,proposalId:string)=>service.confirm({proposalId,linkChangeConfirmed:true});
it('selection and cancellation do not change links; repeated selection retires old tickets',async()=>{const f=await fixture();try{const a=await f.service.prepare('opaque',f.note);expect(await fs.lstat(f.link).catch(()=>null)).toBeNull();f.service.cancel({proposalId:a.proposalId});await expect(apply(f.service,a.proposalId)).rejects.toThrow();const b=await f.service.prepare('opaque',f.note),c=await f.service.prepare('opaque',f.note);await expect(apply(f.service,b.proposalId)).rejects.toThrow();expect(await apply(f.service,c.proposalId)).toEqual({backupPath:null});expect(await fs.readlink(f.link)).toBe(f.note);expect(await fs.readFile(path.join(f.note,'private-note'),'utf8')).toBe('KEEP');}finally{await f.clean();}});
it('preserves an existing different/broken symlink as a private backup and is stable after restart',async()=>{const f=await fixture();try{await fs.mkdir(path.dirname(f.link));const previous=path.join(f.vault,'missing');await fs.symlink(previous,f.link);const p=await f.service.prepare('opaque',f.note);expect(p).toMatchObject({replacement:true,previousTarget:previous,dag:'present'});const result=await apply(f.service,p.proposalId);expect(await fs.readlink(result.backupPath!)).toBe(previous);expect(await fs.readlink(f.link)).toBe(f.note);const restarted=createNoteReconnect(f.options),again=await restarted.prepare('opaque',f.note);expect(again.replacement).toBe(false);expect(await apply(restarted,again.proposalId)).toEqual({backupPath:null});expect(await fs.readlink(result.backupPath!)).toBe(previous);}finally{await f.clean();}});
it('never replaces a regular file, directory or tracked link and keeps their data',async()=>{const f=await fixture();try{await fs.mkdir(path.dirname(f.link));await fs.writeFile(f.link,'KEEP');await expect(f.service.prepare('opaque',f.note)).rejects.toThrow('덮어쓰지');expect(await fs.readFile(f.link,'utf8')).toBe('KEEP');await fs.rm(f.link);await fs.mkdir(f.link);await fs.writeFile(path.join(f.link,'data'),'KEEP');await expect(f.service.prepare('opaque',f.note)).rejects.toThrow('덮어쓰지');expect(await fs.readFile(path.join(f.link,'data'),'utf8')).toBe('KEEP');await fs.rm(f.link,{recursive:true});await fs.symlink(f.note,f.link);execFileSync('/usr/bin/git',['-C',f.tree,'add','docs/note']);await expect(f.service.prepare('opaque',f.note)).rejects.toThrow('Git');}finally{await f.clean();}});
it('rejects invalid directories, permission expansion, unknown projects and recursive links',async()=>{const f=await fixture();try{await expect(f.service.prepare('opaque',path.join(f.root,'missing'))).rejects.toThrow();await expect(f.service.prepare('opaque',path.join(f.note,'private-note'))).rejects.toThrow();await expect(f.service.prepare('other',f.note)).rejects.toThrow();await expect(f.service.prepare('opaque',f.root)).rejects.toThrow('허용 범위 밖');await fs.mkdir(path.join(f.tree,'docs'));await expect(f.service.prepare('opaque',f.tree+'/docs')).rejects.toThrow();}finally{await f.clean();}});
it('rechecks root grant, directory identity and link changes at confirmation',async()=>{const f=await fixture();try{let allowed=true;const s=createNoteReconnect({...f.options,allowed:async()=>allowed});const p=await s.prepare('opaque',f.note);allowed=false;await expect(apply(s,p.proposalId)).rejects.toThrow();expect(await fs.lstat(f.link).catch(()=>null)).toBeNull();allowed=true;const q=await s.prepare('opaque',f.note);await fs.rename(f.note,f.note+'-old');await fs.mkdir(f.note);await expect(apply(s,q.proposalId)).rejects.toThrow();const z=await s.prepare('opaque',f.note);await fs.mkdir(path.dirname(f.link));await fs.writeFile(f.link,'CONCURRENT');await expect(apply(s,z.proposalId)).rejects.toThrow();expect(await fs.readFile(f.link,'utf8')).toBe('CONCURRENT');}finally{await f.clean();}});
it('rejects docs symlink escape and stale main-owned proposals without accepting renderer paths',async()=>{const f=await fixture();try{await fs.symlink(f.vault,path.join(f.tree,'docs'));await expect(f.service.prepare('opaque',f.note)).rejects.toThrow('docs');await fs.rm(path.join(f.tree,'docs'));let now=0;const s=createNoteReconnect({...f.options,now:()=>now}),p=await s.prepare('opaque',f.note);await expect(s.confirm({proposalId:p.proposalId,linkChangeConfirmed:true,path:f.note})).rejects.toThrow();now=120001;await expect(apply(s,p.proposalId)).rejects.toThrow('만료');}finally{await f.clean();}});
it('reports absent DAG separately and never creates note contents',async()=>{const f=await fixture();try{await fs.rm(path.join(f.note,'dag.yaml'));const p=await f.service.prepare('opaque',f.note);expect(p.dag).toBe('absent');await apply(f.service,p.proposalId);expect(await fs.readdir(f.note)).toEqual(['private-note']);}finally{await f.clean();}});
