import {describe,it,expect} from 'vitest';
import {buildProjectModelPack,type ProjectModelSource} from '../../src/main/project-model';
import {SECTION_IDS} from '../../src/summary/reading/model-harness';
function source():ProjectModelSource{return {projectKey:'project:'+'a'.repeat(64),policyProjectId:'work-1',summaryPrefix:'T',mappingIdentity:'test',codeburn:[],dag:{dagId:'dag-1',sourceHash:'b'.repeat(64),sourceMtimeMs:1,observedAt:'2026-10-07T00:00:00Z',doneStatus:'done',readContractVersion:2,policies:[{key:'note_app_status_mapping',legacy:false,decision:{schemaVersion:1,id:'mapping',revision:'r1',scope:{projectId:'work-1'},mappingVersion:'v1',statuses:{committed:{lifecycle:'review'}}}}],tasks:[{id:'T-1',title:'Fictional selected task',status:'committed',rawType:'planning',phase:{id:'P1',title:'Design',index:0},details:{description:'Declared plan reason',acceptanceCriteria:['Review this plan'],targetFiles:['src/example.ts'],discussion:[],design:[],omissions:0},dependencies:[],e2e:{state:'undeclared',required:null,coveredBy:null,coverage:'undeclared'},commitReferences:[],commitVerification:'not-performed'}],statusCounts:[],coverage:{tasksTotal:1,declared:0,required:0,uncoveredDone:[],uncoveredOpen:[],malformed:[]},verifiedFacts:[]},readingSummary:{kind:'rules-only',summaryPrefix:'T',workstreamId:'work-1',fingerprint:'x',revision:1,generatedAt:'2026-10-07T00:00:00Z',checkedAt:'2026-10-07T00:00:00Z',changed:false,partial:false,limitation:'bounded',sections:SECTION_IDS.map(id=>({id,title:id,paragraphs:[{text:'선택 태스크의 선언이며 실제 실행 검증은 미수행입니다.',basis:'declaration',sources:[]}]}))}};}
describe('Phase2 manual task model context',()=>{
 it('binds selected task detail and explicit policy interpretation into cached input',()=>{const s=source(),first=buildProjectModelPack(s),data=first.sources.filter(x=>x.path.startsWith('dag/')).map(x=>x.excerpt).join('\n');expect(data).toContain('Declared plan reason');expect(data).toContain('"lifecycle":"review"');expect(data).toContain('"verificationState":"not-performed"');const policy=s.dag.policies![0].decision as {mappingVersion:string};policy.mappingVersion='v2';expect(buildProjectModelPack(s).sourceSha).not.toBe(first.sourceSha);});
 it('scans policy/detail contents for sensitive data before sending',()=>{const s=source();s.dag.tasks[0].details!.description='private.user@example.invalid';expect(()=>buildProjectModelPack(s)).toThrow('Sensitive input blocked');});
 it('bounds rich details for20 selected tasks without regressing the original DAG byte cap',()=>{const s=source(),original=s.dag.tasks[0];s.dag.tasks=Array.from({length:20},(_,i)=>({...original,id:'T-'+i,details:{...original.details!,description:'설명 '.repeat(500)}}));s.dag.coverage.tasksTotal=20;const pack=buildProjectModelPack(s);expect(Buffer.byteLength(pack.sources.find(x=>x.path==='dag/task-state.json')!.excerpt)).toBeLessThanOrEqual(12000);const details=pack.sources.find(x=>x.path==='dag/selected-details.json')!.excerpt;expect(Buffer.byteLength(details)).toBeLessThanOrEqual(8000);expect(details).toContain('"complete":false');expect(JSON.parse(details).tasks).toHaveLength(20);});

});
