import {taskPrefix} from '../../src/shared/summary-prefix';
import {prefixSelection,scopedDagView,prefixReading} from '../../src/summary/reading/prefix';
import {createModelRetryStorage} from '../../src/summary/reading/model-retry-storage';
import {it,expect,vi} from 'vitest';
import {mkdtemp,realpath,rm,readFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createProjectModelController,buildProjectModelPack,assertSafeModelInput,type ProjectModelSource} from '../../src/main/project-model';
import {createModelReadingStorage} from '../../src/summary/reading/model-reading-storage';
import {readingInputHash,publicInputHash,validateModelAnswer,SECTION_IDS,type ModelAdapter,type ModelBinding,type ReadingModelPack} from '../../src/summary/reading/model-harness';
import {createPublicModelController} from '../../src/main/public-model';
import bundledPublicExample from '../../src/shared/public-reading-pack.json';
// Non-sentinel authored fixture exercises the ordinary controller contract.
const publicPack={...bundledPublicExample,sourceSha:'a'.repeat(40)};
const source=(project='a',text='확인된 문서 근거'):ProjectModelSource=>({projectKey:'project:'+project.repeat(64),mappingIdentity:'local-only',codeburn:[],dag:{dagId:'local-only',sourceHash:'sha256:'+project.repeat(64),sourceMtimeMs:1,observedAt:'2026-10-06T00:00:00.000Z',doneStatus:'done',tasks:[],statusCounts:[],coverage:{tasksTotal:0,declared:0,required:0,uncoveredDone:[],uncoveredOpen:[],malformed:[]},verifiedFacts:[]},readingSummary:{kind:'rules-only',workstreamId:'work-'+project,fingerprint:text,revision:1,generatedAt:'2026-10-06T00:00:00.000Z',checkedAt:'2026-10-06T00:00:00.000Z',changed:false,partial:false,limitation:'bounded',sections:SECTION_IDS.map(id=>({id,title:id,paragraphs:[{text,basis:'declaration',sources:[]}]}))}});
const answer=(binding:ModelBinding,pack:ReadingModelPack)=>({...binding,sections:SECTION_IDS.map(id=>({id,text:pack.facts.filter(f=>f.section===id).map(f=>f.text).join(' '),facts:pack.facts.filter(f=>f.section===id).map(f=>({id:f.id,state:f.state})),sourceIds:[...new Set(pack.facts.filter(f=>f.section===id).flatMap(f=>f.sourceIds))]}))});
async function fixture(){const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'project-model-'))),storage=createModelReadingStorage(path.join(root,'model'));let a=source(),b=source('b');const generate=vi.fn(async({binding,pack})=>({answer:answer(binding,pack),provider:'synthetic-only',runtimeMs:1,usage:{}})) as ModelAdapter['generate'];const options={storage,adapter:{generate},resolve:async(id:string)=>id==='a'?a:b,identify:(id:string)=>id==='a'?a.projectKey:b.projectKey,revision:(id:string)=>id==='a'?a.readingSummary.fingerprint:b.readingSummary.fingerprint};return {root,storage,generate,options,setA:(value:ProjectModelSource)=>{a=value;},clean:()=>rm(root,{recursive:true,force:true})};}
it('binds separate project contracts, stable semantic hashes and current manual scope without weakening public paths',()=>{const a=source(),p=buildProjectModelPack(a),b=buildProjectModelPack(source('b'));expect(readingInputHash(p)).not.toBe(readingInputHash(b));expect(()=>publicInputHash(p as never)).toThrow();const changed=structuredClone(a);changed.dag.observedAt='2026-10-06T01:00:00.000Z';changed.readingSummary={...changed.readingSummary,checkedAt:'2026-10-06T01:00:00.000Z'};expect(readingInputHash(buildProjectModelPack(changed))).toBe(readingInputHash(p));expect(JSON.stringify(p)).not.toContain('local-only');const binding={runId:'fixture',project:p.project,inputHash:readingInputHash(p),version:'connected-project-reading-v2',attempt:1 as const},out=answer(binding,p);expect(validateModelAnswer(out,binding,p)).toEqual([]);out.sections[0].text='기존 모델 실행은 차단되어 있습니다. 확인된 문서 근거';expect(validateModelAnswer(out,binding,p).join()).toContain('F0');p.sources[0].path='documents/../credentials';expect(()=>readingInputHash(p)).toThrow();});
it('blocks credential filenames, obvious secrets and personal information without returning raw data',()=>{for(const [text,file] of [['harmless','.env'],['harmless','credentials.json'],['-----BEGIN PRIVATE KEY-----','doc.md'],['sk-ant-'+ 'a'.repeat(32),'doc.md'],['person@example.test','doc.md'],['010-1234-5678','doc.md']]){expect(()=>assertSafeModelInput(text,file)).toThrow('Sensitive input blocked');if(text!=='harmless')expect(()=>buildProjectModelPack(source('a',text))).toThrow();}});
it('readonly views call no models; same input including controller restart calls once and project bodies remain isolated',async()=>{const f=await fixture();try{const c=createProjectModelController(f.options);await c.view('a');expect(f.generate).not.toHaveBeenCalled();const a=await c.run('a');expect(a.latest.state).toBe('ready');await c.run('a');await createProjectModelController(f.options).run('a');expect(f.generate).toHaveBeenCalledTimes(1);expect((await c.view('b')).latest.state).toBe('empty');const b=await c.run('b');expect(b.latest.state).toBe('ready');expect(f.generate).toHaveBeenCalledTimes(2);expect('latest' in a.latest&&'latest' in b.latest&&a.latest.latest.project!==b.latest.latest.project).toBe(true);}finally{await f.clean();}});
it('changed input failure keeps old success and does not replay or leak adapter errors',async()=>{const f=await fixture();try{const c=createProjectModelController(f.options);const old=await c.run('a');f.setA(source('a','변경된 근거'));const fail=vi.fn(async()=>{throw Error('private failure person@example.test');});const failed=createProjectModelController({...f.options,adapter:{generate:fail}});const result=await failed.run('a');expect(result.state).toBe('failed');expect(result.latest.state).toBe('stale');expect('latest' in result.latest&&'latest' in old.latest&&result.latest.latest.inputHash===old.latest.latest.inputHash).toBe(true);await failed.run('a');expect(fail).toHaveBeenCalledTimes(1);expect(await readFile(path.join(f.root,'model/ledger/summary-cache-v1.json'),'utf8')).not.toContain('person@example');}finally{await f.clean();}});
it('cancel, revoked authority and changed sources cannot publish late results; cross-project concurrency remains one',async()=>{const f=await fixture();try{let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const generate=vi.fn(async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),usage:{},provider:'synthetic-only',runtimeMs:1};});const c=createProjectModelController({...f.options,adapter:{generate}});const flight=c.run('a');await ready;expect((await c.run('b')).state).toBe('failed');f.setA(source('a','권한 또는 근거 변경'));c.invalidate();release();expect((await flight).state).toBe('cancelled');expect((await f.storage.readLatest(source().projectKey)).state).toBe('empty');expect(generate).toHaveBeenCalledTimes(1);}finally{await f.clean();}});
it('public and connected project controllers share the paid global slot and preserve the approved public body',async()=>{const f=await fixture();try{const p=publicPack as import('../../src/summary/reading/model-harness').PublicReadingPack;const publicController=createPublicModelController(p,f.storage,f.options.adapter);await publicController.run();const original=await f.storage.readLatest(p.project);await createProjectModelController(f.options).run('a');expect(await f.storage.readLatest(p.project)).toEqual(original);expect(f.generate).toHaveBeenCalledTimes(2);}finally{await f.clean();}});

it('a busy public model rejects another project without cancelling or racing the public request',async()=>{const f=await fixture();try{let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const generate=vi.fn(async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),provider:'synthetic-only',usage:{},runtimeMs:1};});const p=publicPack as import('../../src/summary/reading/model-harness').PublicReadingPack;const publicController=createPublicModelController(p,f.storage,{generate});const flight=publicController.run();await ready;const other=await createProjectModelController({...f.options,adapter:{generate}}).run('a');expect(other.state).toBe('failed');expect(generate).toHaveBeenCalledTimes(1);release();expect((await flight).state).toBe('idle');expect((await f.storage.readLatest(source().projectKey)).state).toBe('empty');}finally{await f.clean();}});
it('selects review work by status and ID without inferring recency and current CI over older document excerpts and labels unreconciled records',()=>{
  const s=source();s.dag.tasks=Array.from({length:40},(_,i)=>({id:'T-'+String(i+1).padStart(3,'0'),title:'합성 검토 작업',status:'in_review',dependencies:[],e2e:{state:'undeclared',required:null,coveredBy:null,coverage:'undeclared'},commitReferences:[],commitVerification:'not-performed'}));
  s.dag.coverage.tasksTotal=40;
  s.readingSummary={...s.readingSummary,sections:SECTION_IDS.map(id=>({id,title:id,paragraphs:[...Array.from({length:4},(_,i)=>({text:'이전 합성 문서 기록 '+i+' 현재 재대조되지 않음',basis:'declaration' as const,sources:[{kind:'document' as const,id:'old-'+i,sha:'a'.repeat(40),sourceHash:'a'.repeat(64),observedAt:'2026-10-01T00:00:00.000Z'}]})),{text:'현재 합성 CI 검증 성공',basis:'observation' as const,sources:[{kind:'ci' as const,id:'current-ci',sha:'b'.repeat(40),sourceHash:null,observedAt:'2026-10-06T00:00:00.000Z'}]}]}))};
  const p=buildProjectModelPack(s),dag=JSON.parse(p.sources.find(s=>s.path==='dag/task-state.json')!.excerpt);
  expect(dag.tasks[0].id).toBe('T-001');expect(dag.tasks).toHaveLength(20);expect(dag.omitted).toBe(20);
  expect(p.facts.find(f=>f.section==='implemented'&&f.text.includes('우선 확인'))!.text).toContain('T-001');
  expect(p.facts.some(f=>f.section==='evidence'&&f.text==='현재 합성 CI 검증 성공')).toBe(true);
  expect(p.facts.filter(f=>f.text.includes('이전 합성 문서')).every(f=>f.text.includes('현재 미대조')&&f.anchors.includes('현재 미대조'))).toBe(true);
  const binding={runId:'fixture',project:p.project,inputHash:readingInputHash(p),version:'connected-project-reading-v2',attempt:1 as const},out=answer(binding,p);
  expect(validateModelAnswer(out,binding,p)).toEqual([]);out.sections[3].text='과거 기록대로 production model transport 차단이며 별도 승인 필요';expect(validateModelAnswer(out,binding,p).join()).toContain('F1');
});

it('keeps an unchanged running snapshot across ageing while new stale starts remain blocked',async()=>{
 const f=await fixture();let release!:()=>void;try{
  let aged=false,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);
  const resolve=vi.fn(async(id:string,signal:AbortSignal,phase?:'start'|'revalidate')=>{if(aged&&phase==='start')throw Error('Fresh start required');return f.options.resolve(id);});
  const generate=vi.fn(async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),usage:{},provider:'synthetic-only',runtimeMs:1};});
  const c=createProjectModelController({...f.options,resolve,adapter:{generate}}),flight=c.run('a');await ready;aged=true;c.invalidate();release();
  expect((await flight).state).toBe('idle');expect((await f.storage.readLatest(source().projectKey)).state).toBe('ready');expect(resolve.mock.calls.map(c=>c[2])).toEqual(['start','revalidate','revalidate']);
  const stale=await c.run('b');expect(stale.state).toBe('failed');expect(generate).toHaveBeenCalledTimes(1);
 }finally{release?.();await f.clean();}
});
it('still enforces the model deadline and no-replay ledger on a stable snapshot',async()=>{
 const f=await fixture();try{
  const generate=vi.fn((_request,signal:AbortSignal)=>new Promise<never>((_,reject)=>signal.addEventListener('abort',()=>reject(Error('Synthetic deadline')),{once:true})));
  const c=createProjectModelController({...f.options,adapter:{generate},timeoutMs:30});expect((await c.run('a')).state).toBe('failed');expect((await f.storage.readLatest(source().projectKey)).state).toBe('empty');await c.run('a');expect(generate).toHaveBeenCalledTimes(1);
 }finally{await f.clean();}
});

it('records safe preflight failure before any model call and preserves an older body and ledger',async()=>{const f=await fixture();try{const {createModelDiagnostics,ModelDiagnosticError}=await import('../../src/main/model-diagnostics');const diagnostics=createModelDiagnostics(path.join(f.root,'diagnostics'),'a'.repeat(40));await createProjectModelController(f.options).run('a');const ledger=await readFile(path.join(f.root,'model/ledger/summary-cache-v1.json'),'utf8');const previous=await f.storage.readLatest(source().projectKey);const c=createProjectModelController({...f.options,diagnostics,resolve:async()=>{throw new ModelDiagnosticError('dag_cleanup_unverified');}});const result=await c.run('a');expect(result.state).toBe('failed');expect(result.diagnostics!.records[0]).toMatchObject({stage:'source-check',code:'dag_cleanup_unverified',modelCall:'not-started'});expect(f.generate).toHaveBeenCalledTimes(1);expect(await f.storage.readLatest(source().projectKey)).toEqual(previous);expect(await readFile(path.join(f.root,'model/ledger/summary-cache-v1.json'),'utf8')).toBe(ledger);const restarted=await createProjectModelController({...f.options,diagnostics}).view('a');expect(restarted.diagnostics!.records).toEqual(result.diagnostics!.records);expect(f.generate).toHaveBeenCalledTimes(1);}finally{await f.clean();}});
it('logs auth failure and completed duplicate reuse while keeping raw errors out of diagnostics',async()=>{const f=await fixture();try{const {createModelDiagnostics}=await import('../../src/main/model-diagnostics');const diagnostics=createModelDiagnostics(path.join(f.root,'diagnostics'),null);const c=createProjectModelController({...f.options,diagnostics});await c.run('a');const reuse=await c.run('a');expect(reuse.diagnostics!.records[0]).toMatchObject({code:'saved_input_reused',modelCall:'not-started'});f.setA(source('a','다른 합성 근거'));const generate:ModelAdapter['generate']=async(_request,_signal,observe)=>{await observe?.('authentication');throw Error('Existing subscription login required; no model call');};const failed=await createProjectModelController({...f.options,diagnostics,adapter:{generate}}).run('a');expect(failed.diagnostics!.records[0]).toMatchObject({stage:'authentication',code:'subscription_login_required',modelCall:'not-started'});const sensitive=await createProjectModelController({...f.options,diagnostics,resolve:async()=>source('a','private person@example.invalid')}).run('a');expect(sensitive.diagnostics!.records[0].code).toBe('sensitive_input_blocked');expect(await readFile(path.join(f.root,'diagnostics/summary-cache-v1.json'),'utf8')).not.toContain('person@');}finally{await f.clean();}});
it('keeps cancellation and joined/busy requests correlated without issuing another model call',async()=>{const f=await fixture();let release!:()=>void;try{const {createModelDiagnostics}=await import('../../src/main/model-diagnostics');const diagnostics=createModelDiagnostics(path.join(f.root,'diagnostics'),null);let started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const generate=vi.fn(async(_request,signal:AbortSignal,observe?:Parameters<ModelAdapter['generate']>[2])=>{await observe?.('authentication');await observe?.('launch-requested');await observe?.('started');started();await gate;if(signal.aborted)throw Error('Cancelled owned model process');throw Error('PRIVATE person@example.invalid');});const c=createProjectModelController({...f.options,diagnostics,adapter:{generate}}),flight=c.run('a');await ready;const joined=c.run('a');expect((await c.run('b')).diagnostics!.records[0].code).toBe('request_busy');c.cancel('a');release();const result=await flight;await joined;expect(result.state).toBe('cancelled');expect(result.diagnostics!.records.some(r=>r.code==='duplicate_joined')).toBe(true);expect(result.diagnostics!.records.some(r=>r.code==='model_deadline_or_cancelled'&&r.modelCall==='started')).toBe(true);expect(generate).toHaveBeenCalledTimes(1);expect(await readFile(path.join(f.root,'diagnostics/summary-cache-v1.json'),'utf8')).not.toContain('person@');}finally{release?.();await f.clean();}});
it('fails closed before calling a model when diagnostic persistence is unavailable',async()=>{const f=await fixture();try{const {createModelDiagnostics}=await import('../../src/main/model-diagnostics');const diagnostics=createModelDiagnostics(path.join(f.root,'missing-parent/diagnostics'),null);const result=await createProjectModelController({...f.options,diagnostics}).run('a');expect(result.state).toBe('failed');expect(result.diagnostics!.available).toBe(false);expect(f.generate).not.toHaveBeenCalled();}finally{await f.clean();}});

it('distinguishes reuse of failed reservations from successful body reuse and preserves safe process failure metadata',async()=>{const f=await fixture();try{const {createModelDiagnostics}=await import('../../src/main/model-diagnostics');const {ModelProcessFailure}=await import('../../src/summary/reading/model-process-failure');const diagnostics=createModelDiagnostics(path.join(f.root,'diagnostics'),null);let calls=0;const adapter:ModelAdapter={generate:async(_r,_s,observe)=>{calls++;await observe?.('started');throw new ModelProcessFailure('model_exited_unsuccessfully',{exitCode:7,signal:'none',durationMs:3618,outputBytes:0,stderrBytes:30,cleanup:'verified'});}};const controller=createProjectModelController({...f.options,adapter,diagnostics});const failed=await controller.run('a');expect(failed.diagnostics!.records[0]).toMatchObject({code:'model_exited_unsuccessfully',modelCall:'started',process:{exitCode:7}});const reused=await createProjectModelController({...f.options,adapter,diagnostics}).run('a');expect(reused.state).toBe('failed');expect(reused.diagnostics!.records[0]).toMatchObject({code:'saved_failed_input_reused',modelCall:'not-started'});expect(calls).toBe(1);}finally{await f.clean();}});

async function diagnosticFixture(){const f=await fixture();await createProjectModelController(f.options).run('a');f.setA(source('a','동일 실패 입력의 합성 근거'));await createProjectModelController({...f.options,adapter:{generate:async()=>{throw Error('synthetic failure');}}}).run('a');const {createModelDiagnostics}=await import('../../src/main/model-diagnostics');const {createModelRetryStorage}=await import('../../src/summary/reading/model-retry-storage');const diagnostics=createModelDiagnostics(path.join(f.root,'diagnostics'),null);const retryStorage=createModelRetryStorage(path.join(f.root,'retries'),f.storage.lockModelSlot,async(project,hash,run)=> (await f.storage.failedReservation(project,hash))?.runId===run);return {...f,diagnostics,retryStorage,controller:(adapter=f.options.adapter,extra={})=>createProjectModelController({...f.options,adapter,diagnostics,retryStorage,...extra}),ledgerPath:path.join(f.root,'model/ledger/summary-cache-v1.json')};}
const retryRequest=(ticketId:string)=>({ticketId,transferConfirmed:true,oneCallConfirmed:true});
it('runs one explicitly confirmed diagnostic attempt, preserves original ledger/body, blocks duplicate and restart retry',async()=>{const f=await diagnosticFixture();try{const before=await readFile(f.ledgerPath,'utf8'),body=JSON.stringify(await f.storage.readLatest(f.options.identify('a'))),c=f.controller();const p=await c.prepareRetry('a');await expect(c.runRetry({...retryRequest(p.ticketId),path:'/forged'})).rejects.toThrow();const count=vi.mocked(f.generate).mock.calls.length;const pending=c.runRetry(retryRequest(p.ticketId));await expect(c.runRetry(retryRequest(p.ticketId))).rejects.toThrow();const result=await pending;expect(vi.mocked(f.generate).mock.calls.length-count).toBe(1);expect(result.diagnostics!.records[0].code).toBe('diagnostic_retry_succeeded');expect(result.retry).toMatchObject({available:false,used:true});expect(await readFile(f.ledgerPath,'utf8')).toBe(before);expect(JSON.stringify(await f.storage.readLatest(f.options.identify('a')))).toBe(body);await expect(f.controller().prepareRetry('a')).rejects.toThrow('이미');const raw=await readFile(path.join(f.root,'retries/summary-cache-v1.json'),'utf8');expect(raw).not.toContain('동일 실패 입력');expect(raw).not.toContain('answer');expect(raw).not.toContain('receipts');}finally{await f.clean();}});
it('does not perform automatic format repair and stores no failed response body',async()=>{const f=await diagnosticFixture();try{let calls=0;const c=f.controller({generate:async()=>{calls++;return {answer:{PRIVATE_BODY:'DO_NOT_STORE'},usage:{},provider:'synthetic-only',runtimeMs:1};}}),p=await c.prepareRetry('a');const result=await c.runRetry(retryRequest(p.ticketId));expect(calls).toBe(1);expect(result.diagnostics!.records[0].code).toBe('diagnostic_retry_result_invalid');expect(await readFile(path.join(f.root,'retries/summary-cache-v1.json'),'utf8')).not.toMatch(/PRIVATE_BODY|DO_NOT_STORE/);await expect(f.controller().prepareRetry('a')).rejects.toThrow();}finally{await f.clean();}});
it('stops before reserving or calling when current input differs, and cancels unused or expired tickets',async()=>{const f=await diagnosticFixture();try{let now=1;const c=f.controller(f.options.adapter,{now:()=>now}),p=await c.prepareRetry('a');const count=vi.mocked(f.generate).mock.calls.length;c.cancelRetry({ticketId:p.ticketId});await expect(c.runRetry(retryRequest(p.ticketId))).rejects.toThrow();const q=await c.prepareRetry('a');now=120002;await expect(c.runRetry(retryRequest(q.ticketId))).rejects.toThrow();const next=await c.prepareRetry('a');f.setA(source('a','사용자가 바꾼 새 합성 근거'));await c.runRetry(retryRequest(next.ticketId));expect(vi.mocked(f.generate).mock.calls.length).toBe(count);await expect(c.prepareRetry('a')).rejects.toThrow('diagnostic_retry_input_changed');expect((await c.view('a')).diagnostics!.records[0].code).toBe('diagnostic_retry_input_changed');expect(await readFile(path.join(f.root,'retries/summary-cache-v1.json'),'utf8').catch(()=>null)).toBeNull();}finally{await f.clean();}});
it('shares the global model slot, consumes a cancelled reserved retry and keeps stable observations from cancelling its ticket',async()=>{const f=await diagnosticFixture();try{let entered!:()=>void;const ready=new Promise<void>(r=>entered=r),adapter:ModelAdapter={generate:async(_r,signal)=>{entered();return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('Cancelled owned model process')),{once:true}));}};const c=f.controller(adapter),p=await c.prepareRetry('a');c.invalidate();const pending=c.runRetry(retryRequest(p.ticketId));await ready;const other=await createProjectModelController(f.options).run('a');expect(other.state).toBe('failed');c.cancel('a');await pending;await expect(f.controller().prepareRetry('a')).rejects.toThrow('이미');const bytes=await readFile(path.join(f.root,'retries/summary-cache-v1.json'),'utf8');expect(bytes).toContain('cancelled');}finally{await f.clean();}});
it('fails closed on corrupt retry persistence before any model start',async()=>{const f=await diagnosticFixture();try{const {mkdir,writeFile}=await import('node:fs/promises');await mkdir(path.join(f.root,'retries'),{mode:0o700});await writeFile(path.join(f.root,'retries/summary-cache-v1.json'),'KEEP_CORRUPT',{mode:0o600});const count=vi.mocked(f.generate).mock.calls.length;await expect(f.controller().prepareRetry('a')).rejects.toThrow();expect(vi.mocked(f.generate).mock.calls.length).toBe(count);expect(await readFile(path.join(f.root,'retries/summary-cache-v1.json'),'utf8')).toBe('KEEP_CORRUPT');}finally{await f.clean();}});
it('rejects a symlink retry store without touching its target or invoking a model',async()=>{const f=await diagnosticFixture();try{const {mkdir,symlink}=await import('node:fs/promises');const outside=path.join(f.root,'outside');await mkdir(outside,{mode:0o700});await symlink(outside,path.join(f.root,'retries'));const count=vi.mocked(f.generate).mock.calls.length;await expect(f.controller().prepareRetry('a')).rejects.toThrow();expect(vi.mocked(f.generate).mock.calls.length).toBe(count);expect(await readFile(path.join(outside,'summary-cache-v1.json'),'utf8').catch(()=>null)).toBeNull();}finally{await f.clean();}});

function scopedSource(prefix:string,key='b'):ProjectModelSource {
 const s=source(key);s.summaryPrefix=prefix;s.readingSummary={...s.readingSummary,summaryPrefix:prefix};
 s.dag.tasks=[{id:prefix+'-002c',title:'Selected '+prefix,status:'pending',dependencies:[{id:'OUT-001',scope:'internal'}],e2e:{state:'undeclared',required:null,coveredBy:null,coverage:'undeclared'},commitReferences:[],commitVerification:'not-performed'}];s.dag.coverage.tasksTotal=1;s.dependencyObservations=[{id:'OUT-001',scope:'internal',status:'done'}];return s;
}
it('parses exact prefixes and suffixes; full-model filtering excludes other bodies while retaining dependency metadata',()=>{
 expect(['T-227','MP-002c','TT-002','T-019a-1','not-a-task'].map(taskPrefix)).toEqual(['T','MP','TT','T',null]);
 const s=scopedSource('MP');s.dag.tasks=Array.from({length:210},(_,i)=>({...s.dag.tasks[0],id:'MP-'+i,title:'Other body'}));s.dag.tasks.push({...s.dag.tasks[0],id:'T-227',title:'Chosen late item',dependencies:[{id:'MP-0',scope:'internal'}]}, {...s.dag.tasks[0],id:'TT-001'});
 const {tasks,scope}=prefixSelection(s.dag,'T');expect(tasks.map(t=>t.id)).toEqual(['T-227']);expect(scope.dependencies).toEqual([{id:'MP-0',scope:'internal',status:'pending'}]);expect(JSON.stringify(scope)).not.toContain('Other body');const hash=scope.sourceHash;s.dag.tasks[0].title='Changed other body';expect(prefixSelection(s.dag,'T').scope.sourceHash).toBe(hash);s.dag.tasks[0].status='done';expect(prefixSelection(s.dag,'T').scope.sourceHash).not.toBe(hash);
 const scoped=scopedSource('T');scoped.dag={...s.dag,tasks,coverage:{...s.dag.coverage,tasksTotal:1}};scoped.dependencyObservations=scope.dependencies;
 const pack=buildProjectModelPack(scoped);expect(JSON.stringify(pack)).toContain('Chosen late item');expect(JSON.stringify(pack)).not.toContain('Other body');expect(JSON.stringify(pack)).not.toContain('TT-001');scoped.dag.tasks.push(s.dag.tasks[0]);expect(()=>buildProjectModelPack(scoped)).toThrow('Current bounded source unavailable');
});
it('separates prefix results and failed reservations across switches and restart, preserving legacy records',async()=>{
 const f=await fixture();try{const legacy=createProjectModelController(f.options);await legacy.run('a');const legacyBefore=await f.storage.readLatest(source().projectKey);const t=scopedSource('T','b'),mp=scopedSource('MP','c');f.setA(t);const c=createProjectModelController(f.options);
 expect((await c.view('a')).latest.state).toBe('empty');await c.run('a');const saved=await f.storage.readLatest(t.projectKey);f.setA(mp);c.invalidate();const switched=await c.view('a');expect(switched.inputHash).toBeNull();expect(switched.latest.state).toBe('empty');await c.run('a');f.setA(t);c.invalidate();expect((await c.view('a')).latest.state).toBe('stale');expect((await createProjectModelController(f.options).view('a')).latest.state).toBe('stale');expect(await f.storage.readLatest(t.projectKey)).toEqual(saved);expect(await f.storage.readLatest(source().projectKey)).toEqual(legacyBefore);
 const retryStorage=createModelRetryStorage(path.join(f.root,'retry'),async()=>async()=>{},async()=>true);const fail=createProjectModelController({...f.options,retryStorage,adapter:{generate:async()=>{throw Error('synthetic failed');}}});f.setA(scopedSource('T','d'));await fail.run('a');expect((await fail.view('a')).retry?.available).toBe(true);f.setA(mp);fail.invalidate();expect((await fail.view('a')).retry?.available).toBe(false);expect((await fail.view('a')).state).toBe('idle');f.setA(scopedSource('T','d'));expect((await fail.view('a')).retry?.available).toBe(true);
 }finally{await f.clean();}
});
it('prefix change cancels pending synthetic output and prevents publication to either scope',async()=>{
 const f=await fixture();try{const t=scopedSource('T','b');f.setA(t);let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const c=createProjectModelController({...f.options,adapter:{generate:async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),provider:'synthetic-only',runtimeMs:1,usage:{}};}}});const flight=c.run('a');await ready;const mp=scopedSource('MP','c');f.setA(mp);c.invalidate();release();await flight;expect((await c.view('a')).inputHash).toBeNull();expect((await f.storage.readLatest(t.projectKey)).state).toBe('empty');expect((await f.storage.readLatest(mp.projectKey)).state).toBe('empty');
 }finally{await f.clean();}
});
