import {it,expect,vi} from 'vitest';
import {mkdtemp,realpath,rm,readFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createProjectModelController,buildProjectModelPack,assertSafeModelInput,type ProjectModelSource} from '../../src/main/project-model';
import {createModelReadingStorage} from '../../src/summary/reading/model-reading-storage';
import {readingInputHash,publicInputHash,validateModelAnswer,SECTION_IDS,type ModelAdapter,type ModelBinding,type ReadingModelPack} from '../../src/summary/reading/model-harness';
import {createPublicModelController} from '../../src/main/public-model';
import publicPack from '../../src/shared/public-reading-pack.json';
const source=(project='a',text='확인된 문서 근거'):ProjectModelSource=>({projectKey:'project:'+project.repeat(64),mappingIdentity:'local-only',codeburn:[],dag:{dagId:'local-only',sourceHash:'sha256:'+project.repeat(64),sourceMtimeMs:1,observedAt:'2026-10-06T00:00:00.000Z',doneStatus:'done',tasks:[],statusCounts:[],coverage:{tasksTotal:0,declared:0,required:0,uncoveredDone:[],uncoveredOpen:[],malformed:[]},verifiedFacts:[]},readingSummary:{kind:'rules-only',workstreamId:'work-'+project,fingerprint:text,revision:1,generatedAt:'2026-10-06T00:00:00.000Z',checkedAt:'2026-10-06T00:00:00.000Z',changed:false,partial:false,limitation:'bounded',sections:SECTION_IDS.map(id=>({id,title:id,paragraphs:[{text,basis:'declaration',sources:[]}]}))}});
const answer=(binding:ModelBinding,pack:ReadingModelPack)=>({...binding,sections:SECTION_IDS.map(id=>({id,text:pack.facts.filter(f=>f.section===id).map(f=>f.text).join(' '),facts:pack.facts.filter(f=>f.section===id).map(f=>({id:f.id,state:f.state})),sourceIds:[...new Set(pack.facts.filter(f=>f.section===id).flatMap(f=>f.sourceIds))]}))});
async function fixture(){const root=await realpath(await mkdtemp(path.join(os.tmpdir(),'project-model-'))),storage=createModelReadingStorage(path.join(root,'model'));let a=source(),b=source('b');const generate=vi.fn(async({binding,pack})=>({answer:answer(binding,pack),provider:'synthetic-only',runtimeMs:1,usage:{}})) as ModelAdapter['generate'];const options={storage,adapter:{generate},resolve:async(id:string)=>id==='a'?a:b,identify:(id:string)=>id==='a'?a.projectKey:b.projectKey,revision:(id:string)=>id==='a'?a.readingSummary.fingerprint:b.readingSummary.fingerprint};return {root,storage,generate,options,setA:(value:ProjectModelSource)=>{a=value;},clean:()=>rm(root,{recursive:true,force:true})};}
it('binds separate project contracts, stable semantic hashes and current manual scope without weakening public paths',()=>{const a=source(),p=buildProjectModelPack(a),b=buildProjectModelPack(source('b'));expect(readingInputHash(p)).not.toBe(readingInputHash(b));expect(()=>publicInputHash(p as never)).toThrow();const changed=structuredClone(a);changed.dag.observedAt='2026-10-06T01:00:00.000Z';changed.readingSummary={...changed.readingSummary,checkedAt:'2026-10-06T01:00:00.000Z'};expect(readingInputHash(buildProjectModelPack(changed))).toBe(readingInputHash(p));expect(JSON.stringify(p)).not.toContain('local-only');const binding={runId:'fixture',project:p.project,inputHash:readingInputHash(p),version:'connected-project-reading-v1',attempt:1 as const},out=answer(binding,p);expect(validateModelAnswer(out,binding,p)).toEqual([]);out.sections[0].text='기존 모델 실행은 차단되어 있습니다. 확인된 문서 근거';expect(validateModelAnswer(out,binding,p).join()).toContain('F0');p.sources[0].path='documents/../credentials';expect(()=>readingInputHash(p)).toThrow();});
it('blocks credential filenames, obvious secrets and personal information without returning raw data',()=>{for(const [text,file] of [['harmless','.env'],['harmless','credentials.json'],['-----BEGIN PRIVATE KEY-----','doc.md'],['sk-ant-'+ 'a'.repeat(32),'doc.md'],['person@example.test','doc.md'],['010-1234-5678','doc.md']]){expect(()=>assertSafeModelInput(text,file)).toThrow('Sensitive input blocked');if(text!=='harmless')expect(()=>buildProjectModelPack(source('a',text))).toThrow();}});
it('readonly views call no models; same input including controller restart calls once and project bodies remain isolated',async()=>{const f=await fixture();try{const c=createProjectModelController(f.options);await c.view('a');expect(f.generate).not.toHaveBeenCalled();const a=await c.run('a');expect(a.latest.state).toBe('ready');await c.run('a');await createProjectModelController(f.options).run('a');expect(f.generate).toHaveBeenCalledTimes(1);expect((await c.view('b')).latest.state).toBe('empty');const b=await c.run('b');expect(b.latest.state).toBe('ready');expect(f.generate).toHaveBeenCalledTimes(2);expect('latest' in a.latest&&'latest' in b.latest&&a.latest.latest.project!==b.latest.latest.project).toBe(true);}finally{await f.clean();}});
it('changed input failure keeps old success and does not replay or leak adapter errors',async()=>{const f=await fixture();try{const c=createProjectModelController(f.options);const old=await c.run('a');f.setA(source('a','변경된 근거'));const fail=vi.fn(async()=>{throw Error('private failure person@example.test');});const failed=createProjectModelController({...f.options,adapter:{generate:fail}});const result=await failed.run('a');expect(result.state).toBe('failed');expect(result.latest.state).toBe('stale');expect('latest' in result.latest&&'latest' in old.latest&&result.latest.latest.inputHash===old.latest.latest.inputHash).toBe(true);await failed.run('a');expect(fail).toHaveBeenCalledTimes(1);expect(await readFile(path.join(f.root,'model/ledger/summary-cache-v1.json'),'utf8')).not.toContain('person@example');}finally{await f.clean();}});
it('cancel, revoked authority and changed sources cannot publish late results; cross-project concurrency remains one',async()=>{const f=await fixture();try{let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const generate=vi.fn(async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),usage:{},provider:'synthetic-only',runtimeMs:1};});const c=createProjectModelController({...f.options,adapter:{generate}});const flight=c.run('a');await ready;expect((await c.run('b')).state).toBe('failed');f.setA(source('a','권한 또는 근거 변경'));c.invalidate();release();expect((await flight).state).toBe('cancelled');expect((await f.storage.readLatest(source().projectKey)).state).toBe('empty');expect(generate).toHaveBeenCalledTimes(1);}finally{await f.clean();}});
it('public and connected project controllers share the paid global slot and preserve the approved public body',async()=>{const f=await fixture();try{const p=publicPack as import('../../src/summary/reading/model-harness').PublicReadingPack;const publicController=createPublicModelController(p,f.storage,f.options.adapter);await publicController.run();const original=await f.storage.readLatest(p.project);await createProjectModelController(f.options).run('a');expect(await f.storage.readLatest(p.project)).toEqual(original);expect(f.generate).toHaveBeenCalledTimes(2);}finally{await f.clean();}});

it('a busy public model rejects another project without cancelling or racing the public request',async()=>{const f=await fixture();try{let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r),gate=new Promise<void>(r=>release=r);const generate=vi.fn(async({binding,pack})=>{started();await gate;return {answer:answer(binding,pack),provider:'synthetic-only',usage:{},runtimeMs:1};});const p=publicPack as import('../../src/summary/reading/model-harness').PublicReadingPack;const publicController=createPublicModelController(p,f.storage,{generate});const flight=publicController.run();await ready;const other=await createProjectModelController({...f.options,adapter:{generate}}).run('a');expect(other.state).toBe('failed');expect(generate).toHaveBeenCalledTimes(1);release();expect((await flight).state).toBe('idle');expect((await f.storage.readLatest(source().projectKey)).state).toBe('empty');}finally{await f.clean();}});
