import {describe,it,expect} from 'vitest';
import {selectSummaryTasks} from '../../src/summary/reading/task-selection';
import {prefixSelection,scopedDagView,prefixReading} from '../../src/summary/reading/prefix';
import {buildProjectModelPack} from '../../src/main/project-model';
import {readingInputHash,validateModelAnswer,SECTION_IDS} from '../../src/summary/reading/model-harness';
import type {DagTask,DagReadModel} from '../../src/facts/dag-read-model';
import type {LiveDagView,LiveWorkstreamView} from '../../src/shared/live';
const task=(id:string,status='done',deps:string[]=[]):DagTask=>({id,title:'Task '+id,status,dependencies:deps.map(id=>({id,scope:'internal'})),e2e:{state:'undeclared',required:null,coveredBy:null,coverage:'undeclared'},commitReferences:[],commitVerification:'not-performed'});
function fixture(){const tasks=Array.from({length:463},(_,i)=>task('T-'+i));tasks[450]=task('T-450','blocked',['MP-1']);tasks[451]=task('T-451','running');tasks[452]=task('T-452','in_review');tasks[453]=task('T-453','pending');tasks[454]=task('T-454','pending',['T-450']);tasks[455]=task('T-455','pending',['T-450']);tasks.push({...task('MP-1','pending'),title:'OTHER_PREFIX_SECRET_BODY'});const model:DagReadModel={dagId:'fixture',doneStatus:'done',sourceHash:'sha256:'+ 'a'.repeat(64),sourceMtimeMs:1,observedAt:'2026-10-07T00:00:00.000Z',tasks,statusCounts:[],coverage:{tasksTotal:tasks.length,declared:0,required:0,uncoveredDone:[],uncoveredOpen:[],malformed:[]},verifiedFacts:[]};return model;}
const base={dagId:'fixture',state:'ready',doneStatus:'done',observedAt:'2026-10-07T00:00:00.000Z'} as LiveDagView;
const work={id:'fictional',noteMapping:{state:'resolved',dagId:'fixture'}} as LiveWorkstreamView;
function source(model:DagReadModel,explicit?:string[]){const {tasks,scope}=prefixSelection(model,'T',explicit),dag=scopedDagView(base,model,'T',200,explicit);return {projectKey:'project:'+ 'b'.repeat(64),summaryPrefix:'T',taskSelection:scope.taskSelection,dependencyObservations:scope.dependencies,readingSummary:prefixReading(work,dag),dag:{...model,tasks},mappingIdentity:'fixture',codeburn:[]};}
describe('task-scoped summary selection',()=>{
 it('represents 463 tasks without losing old blockers, late active tasks or high downstream impact',()=>{const model=fixture(),s=prefixSelection(model,'T').scope.taskSelection;expect(s.taskIds).toHaveLength(20);expect(s.omittedCount).toBe(443);expect(s.taskIds).toEqual(expect.arrayContaining(['T-450','T-451','T-452','T-453']));expect(s.reasons.find(r=>r.id==='T-450')).toMatchObject({reason:'차단 선언',waitingCount:2});expect(prefixSelection({...model,sourceMtimeMs:999999,observedAt:'2030-01-01'},'T').scope.taskSelection).toEqual(s);
 const tasks=Array.from({length:100},(_,i)=>task('T-'+i,'blocked'));tasks.push(...Array.from({length:10},(_,i)=>task('T-'+(100+i),'pending',['T-90'])));expect(selectSummaryTasks(tasks,tasks,'done').taskIds[0]).toBe('T-90');
 });
 it('uses exactly the same selected IDs in rules and AI and only outside dependency ID/status',()=>{const s=source(fixture()),p=buildProjectModelPack(s),dag=JSON.parse(p.sources.find(s=>s.path==='dag/task-state.json')!.excerpt);expect(dag.tasks.map((t:DagTask)=>t.id)).toEqual(s.readingSummary.summaryTaskIds);expect(dag.omitted).toBe(443);expect(JSON.stringify(s.readingSummary)).toContain('T-450');expect(JSON.stringify(p)).toContain('최신');expect(JSON.stringify(p)).not.toContain('OTHER_PREFIX_SECRET_BODY');expect(s.dependencyObservations).toContainEqual({id:'MP-1',scope:'internal',status:'pending'});expect(JSON.stringify(s.readingSummary.sections.find(s=>s.id==='next'))).not.toContain('T-454 Task T-454은');
 const binding={runId:'fixture',project:p.project,inputHash:readingInputHash(p),version:'connected-project-reading-v2',attempt:1 as const};const answer={...binding,sections:SECTION_IDS.map(id=>({id,text:p.facts.filter(f=>f.section===id).map(f=>f.text).join(' '),facts:p.facts.filter(f=>f.section===id).map(f=>({id:f.id,state:f.state})),sourceIds:[...new Set(p.facts.filter(f=>f.section===id).flatMap(f=>f.sourceIds))]}))};expect(validateModelAnswer(answer,binding,p)).toEqual([]);answer.sections[0].facts=[];expect(validateModelAnswer(answer,binding,p).join()).toContain('Missing fact coverage');
 });
 it('explicit tasks beyond UI 200 override representatives and preserve same-prefix dependency blocking',()=>{const s=source(fixture(),['T-454']),p=buildProjectModelPack(s);expect(s.readingSummary.summaryTaskIds).toEqual(['T-454']);expect(s.dependencyObservations).toContainEqual({id:'T-450',scope:'internal',status:'blocked'});expect(JSON.parse(p.sources.find(s=>s.path==='dag/task-state.json')!.excerpt).tasks.map((t:DagTask)=>t.id)).toEqual(['T-454']);expect(JSON.stringify(s.readingSummary)).not.toContain('다음 구현 후보입니다');expect(JSON.stringify(p)).not.toContain('Task T-451');expect(scopedDagView(base,fixture(),'T',200,['T-454']).tasks[0].id).toBe('T-454');});
 it('does not silently replace a disappeared selection, and isolates task input hashes',()=>{const model=fixture(),a=source(model,['T-454']),b=source(model,['T-455']);expect(readingInputHash(buildProjectModelPack(a))).not.toBe(readingInputHash(buildProjectModelPack(b)));model.tasks=model.tasks.filter(t=>t.id!=='T-454');const missing=source(model,['T-454']);expect(missing.taskSelection.missingIds).toEqual(['T-454']);expect(missing.taskSelection.taskIds).toEqual([]);expect(()=>buildProjectModelPack(missing)).toThrow();});
 it('keeps omitted sensitive input checks and DAG byte limits',()=>{const model=fixture();model.tasks[10].title='person@example.test';expect(()=>buildProjectModelPack(source(model,['T-454']))).toThrow('Sensitive input blocked');const s=source(fixture(),['T-454']);s.dag.tasks.find(t=>t.id==='T-454')!.title='x'.repeat(13000);expect(()=>buildProjectModelPack(s)).toThrow();});
});
